src/image.jsx
The way it is now if you try to set the `display` property of an `Image` it is overwritten by the defaults.
This PR moves the styles from props to the end of the assign call they will always override the defaults.
=> Passed props should override defaults

src/spectacle.jsx
This typo makes the import not work on my machine
Some versions of what I use:
```
node v0.10.25
npm 1.3.10
webpack 1.10.1
```
=> Correct typo in imports

package.json
If you don’t already have Surge installed with `npm install -g surge`, the `npm run deploy` command will fail. This fixes the issue by adding `surge` as a `devDependency` in the `package.json`.
=> Adds Surge as a development dependency for deployment

webpack.config.js
Hot loading was broken in [this commit](https://github.com/FormidableLabs/spectacle/commit/12831ca2bfdced87ec8d00a7b3292bf3f796db4a)
`hjs-webpack` enables hotloading when running with `webpack-dev-server` [here](https://github.com/HenrikJoreteg/hjs-webpack/blob/a8d771bd99870706e7f0e20a69aea89c6c836d92/index.js#L106)
This PR will always leave hot loading on.
If you'd like I can only turn on hot loading when running with `webpack-dev-server` the same way that `hjs-webpack` does it by wrapping in an if `isDev` where ...
`var isDev = process.argv[1].indexOf('webpack-dev-server') !== -1`
Lemme know and I'll update the PR...
=> Fix hot loading

src/deck.jsx
Just gave a talk with one of those presenter remotes and it used page up and page down to move through the slides.
I threw this in before the talk and it went great :smile: 
The same presenter remote worked fine with [reveal.js](https://github.com/hakimel/reveal.js/blob/eff2265bbd6d892ae2316edff748754b4b0c4798/js/reveal.js#L3808-L3811) so i'm assuming its standard.
=> add support for page up & page down

README.markdown, src/appear.jsx, src/slide.jsx
I think i found a way to remove the need of fid in Appear. Not really the `react` way but well, it works. Check it out
=> remove fid from Appear

README.markdown
Quick fix on the link link to http://localhost:3000/#/?presenter – didn't have the query param in the `href`, now it does. :smile:
=> Add presenter query param to presenter link

themes/default/index.js, themes/default/print.js
This PR replaces `em` with `rem`. This fixes the font styling of inline code (#88) and nested lists (#75).
=> Use relative em units

README.markdown, src/deck.jsx
The o key and p key currently drive the overview and presenter views.
This poses a problem when building an interactive component with a textbox or textarea within a slide. If the o or p key is pressed while in a text input, the slideshow will go into that mode, which may be unexpected behavior to a lot of people.
This pull request requires the alt key to be pressed in conjunction with the p key and the
o to trigger the overview and presenter views.
=> Change keys for Presenter and Overview

src/components/code-pane.js, src/components/markdown.js
When running `npm start` I got an error that `lodash/lang/isundefined` could not be resolved (used in `code-pane.js` and `markdown.js`).
I'm not sure why it couldn't resolve it (the path seems to be right), but this PR fixes it.
=> Fix import statement for lodash/lang/isUndefined

src/store/index.js
createLogger was imported but not used. Fixes the error:
"Module not found: Error: Cannot resolve module 'redux-logger'"
=> Remove redux-logger import

webpack.config.js, webpack.config.production.js
Safari lacks es6 Object.assign. This uses the solution from
http://stackoverflow.com/a/32917654 to add the babel-core polyfill which
fixes support for Safari (and potentially other polyfills?).
Not entirely sure this is the right solution, but it does work for me. Tested by making the same changes to the webpack.config.js files in spectacle-boilerplate.
=> Use babel-core polyfill for Safari.

assets/deck.example, package.json, presentation/index.js
`react-router` was removed in `1.0.0` but there are still references to it in `package.json` and the example slides. This pull request deletes references to `react-router`.
=> Remove references to react-router

.npmignore
to be able to use spectacle via npmcdn.com
=> exclude dist from npmignore

src/components/presenter.js
I didn’t update the proptype for this since I’m using the github editor since that is a professional developer tool for professional developers like me.
=> Allow notes to be JSX elements

README.markdown
I cloned the boilerplate and clicked the links in this README; did not have the intended effect. This commit updates the links so that the boilerplate works.
=> Remove `#` from links

README.markdown
Small update to ReadMe to import `Spectacle` Component, rather than `S`. 
I thought this was better than
`import { S as Spectacle } from 'spectacle`
=> update readme example to import Spectacle component rather than S

src/utils/base.js
I need to do this for 99% of my slides in a presentation:
```js
<Slide bgImage={images.name} bgSize="contain" bgRepeat="no-repeat">
```
I also added `bgPosition` for consistency.
=> Add bg{Size,Position,Repeat} to base

README.markdown
The readme [states](https://github.com/FormidableLabs/spectacle#slide-base) that a slide's `align` property takes two values, both of which can either by `flex-start` or `center` or `flex-end`, but then states that the default is `align="center middle"`, which should actually be `align="center center"` I think, so that change has been made. Also changed `it's` to `its` on line 241 (the same line).
Spectacle is awesome, by the way, thanks for making this :+1:
=> Fix alignment typo in README

package.json
It seems the history module at v1.13.1 doesn't properly build on install in a cross-platform way.
This resolves windows installation problems & a related CI problem with the spectacle editor.
=> update history to v2.1.1

README.markdown
I checked the Link Component, and it supports passing in the `target` attribute in as a `prop` but it wasn't documented.
Also the deleted space I believe was my editor. I can put the space back if you need, let me know!
Thanks!
=> Add Link Target Documentation in README

src/utils/context.js, src/utils/controller.js
Previously, a unique react component class was generated for every `render()` of `controller.js`. This caused the entire slide deck DOM to be replaced during every transition. 
/cc @kenwheeler
=> Fix generation of new react component class during render of context wrapper

src/components/presenter.js
Kinda hacky the way this works, but it does work!
=> Add updateNotes context function for spectacle-code-slide

docs/api/api-docs.md, docs/api/basic-concepts.md, docs/api/extensions.md, docs/api/props-docs.md, docs/getting-started.md
cc/ @kenwheeler 
This sets up the basic structure for docs within the Spectacle lander under the new content components structure for Formidable Landers (see: https://github.com/FormidableLabs/formidable-landers/wiki/Content-Components-(Outline)-for-Landers).
Copy is NOT FINAL and will be changed once structure is complete. This was all just copied over verbatim from the repo Readme. This purely sets up the structure for how this will be pulled into the spectacle-docs repo to set up various pages within the larger "docs" section of the lander.
Let me know if you have any qs about all this!
=> adding new docs structure

docs/api/basic-concepts.md
updating the header on the basic concepts page for the docs from an H2 to an H1 for better syntax and stylistic purposes
=> updating the basic concepts header from h2 to h1

README.markdown, src/components/list.js
This PR adds ordered list functionality to the `List` component, in order to enable functionality as described [here](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ol). Supported props in ordered lists are:
* reversed
* start (index to start numbering)
* type (lettered, numbered, Roman numerals...)
```jsx
// Capital letter list starting from 2
<List ordered start={2} type="A">
<ListItem></ListItem>
</List>
```
=> Add support for ordered list in `List`component

src/components/slide.js
Global mutation of documentElement style was breaking the site containing the spectacle presentation. If I'm understanding the slide's `viewerScaleMode` prop correctly, then when it's true, setting the documentElement's fontSize won't make a difference anyway.
=> Don't set documentElement fontSize when slide viewerScaleMode is true

README.markdown
Current URLs in documentation don't work.
See https://github.com/FormidableLabs/spectacle/issues/218
=> Improve presenter and export URL documentation

src/components/deck.js
Currently we cannot pass arrays of `<Slide>`s to `<Deck>`, such as
```js
<Spectacle theme={theme}>
<Deck transition={["zoom", "slide"]} transitionDuration={200} progress="bar">
{mds.map(md => <Markdown source={md}/>)}
</Deck>
</Spectacle>
```
It would be great if we could!
`<Deck>` treats `this.props.children` directly.
`this.props.children` may include arrays as the element like:
`[<Slide/>, [<Slide/>, <Slide/>], <Slide/>]`
So `this.props.children.length` returns `3` while it actually has `4` slides.
However, in some methods `Deck` treats children with `React.Children`.
```js
import { Children } from 'react';
assert.deepEqual(this.props.children, [<Slide/>, [<Slide/>, <Slide/>], <Slide/>]);
this.props.children.length; // 3;
const children = Children.toArray(this.props.children); // …
```
=> Accept arrays of `Slide` in `Deck`

README.markdown, package.json, src/components/__snapshots__/deck.test.js.snap, src/components/__snapshots__/typeface.test.js.snap, src/components/block-quote.js, src/components/cite.js, src/components/deck.js, src/components/deck.test.js, src/components/heading.js, src/components/link.js, src/components/list-item.js, src/components/quote.js, src/components/table-header-item.js, src/components/table-item.js, src/components/text.js, src/components/transitionable.test.js, src/components/typeface.js, src/components/typeface.test.js, src/index.js, src/themes/default/screen.js
* Themes can now load a system font or Google Font
* Google Font style tags will be automatically created and appended to DOM
* `<Typeface />` tag can be used for specific font styling of text
* Added and documented changes and examples to README
Addresses #233 
=> Add Typeface tag and Google Font support to themes.

example/src/index.js, webpack.config.js, webpack.config.production.js
On a fresh install, `npm start` returns:
```
Module not found: Error: Can't resolve 'babel' in '/_dir/spectacle'
BREAKING CHANGE: It's no longer allowed to omit the '-loader' prefix when using loaders.
You need to specify 'babel-loader' instead of 'babel'.
```
This fixes the problem.
=> add webpack -loader suffixes

package.json, yarn.lock
Ensured yarn and npm both install the latest version of enzyme-to-json so child text strings are properly rendered in the snapshot tests.
=> Update yarn.lock with enzyme to json 1.4.5

src/components/__snapshots__/presenter.test.js.snap, src/components/presenter.js
Addresses #214 
This reorganizes the presenter screen to make more room for slide notes:
=> Reorganize presenter screen to make room for notes

src/utils/base.js
Fixes a typo when checking the `NODE_ENV` in `getStyles`.
=> Fix typo in getStyles

src/components/table.js
Any `<table>` HTML element must have a `<tbody>`. React is also nagging:
This patch adds a `<tbody>` to the `<Table>` component.
=> Fix invalid DOM nesting in <Table>

README.markdown, example/src/index.js, package.json, src/components/__snapshots__/table-body.test.js.snap, src/components/__snapshots__/table-header.test.js.snap, src/components/__snapshots__/table.test.js.snap, src/components/table-body.js, src/components/table-body.test.js, src/components/table-header.js, src/components/table-header.test.js, src/components/table.js, src/index.js, yarn.lock
* Upgrade to React 15.4.2
* Add docs for new tags and example slide
=> Add Table Header / Body.

README.markdown, src/components/component-playground.js, src/components/component-playground.test.js
Hi Spectacle team! 🙋 Thanks for all your hard work, I'm loving it so far! I wanted to request a feature to pass in a custom component or outside module via the scope prop to ComponentPlayground.
Here's what I did to accomplish this:
- Added scope prop to ComponentPlayground that connects to existing functionality in ReactPlayground from the `component-playground` module
- Updated README to document new prop
- Added test to cover new functionality
Now, you can pass in third-party components & change them on the fly!
=> Added feature to pass custom component to ComponentPlayground

src/utils/preloader.js
In `example/src/index.js`, we are using `preload` like this:
```js
const images = {
city: require("../assets/city.jpg"),
kat: require("../assets/kat.png"),
logo: require("../assets/formidable-logo.svg"),
markdown: require("../assets/markdown.png")
};
preloader(images);
```
...which is not an array, so images were not actually being preloaded. This updates `preload` to work with both arrays and objects.
=> Fix preloader to accept an array or object

src/components/manager.js
Addresses #299 and #159 
Adds a default transition prop to prevent transition is undefined error when neither `Deck` or `Slide` have transition props
=> Add default transition prop

src/components/markdown-slides.js, src/components/markdown.js
Pass the override elements as prescribed by Marksy API.
=> Correctly pass the options to marksy

README.markdown
What it says on the tin. Just a documentation change as discussed in #326.
What your strategy around updating https://formidable.com/open-source/spectacle/docs/? Do you want a PR against spectacle-docs as well?
=> add warning re: deployment to GitHub Pages and dist dir path

src/components/transitionable.js
Defect since introduction of SlideSet in 49b191723591f8aa4f18004a3268256298cde720 in January.
The wrong transition direction is especially visible on forward "slide" transitions.
=> Fix direction of slide transition

README.markdown, src/components/__snapshots__/markdown-slides.test.js.snap, src/components/markdown.js
This pr fixes issue about #329.
In README, Markdown tag has property 'source'. But, It has no usage on codes. 
So Markdown class will pass 'null' or 'undefined' value to marked.js, `str.replace` method makes exception in conclusion.
I think this commit makes bugs. (Changes markdown passing logic?)
https://github.com/FormidableLabs/spectacle/commit/fe8607de3ed12e58bc0705a2351f5152dd1de4e0#diff-600386b6077350650f252d685cbe2565
And, I found that `mdastConfig` property has removed on that commit, So I removed it from README.md together.
=> Fix issue #329

src/components/__snapshots__/manager.test.js.snap, src/components/__snapshots__/markdown-slides.test.js.snap, src/components/manager.js, src/components/transitionable.js
Use the manager’s slide reference to properly look up the route’s slide index.
The "slide" transition animation is broken when moving backward in slides with string based id hashes. The wrong transition direction gets visible if two slides with string hashes are in a row, transition "slide" is used and you are navigating backward.
=> Fix transition direction of slides with string based hashes

src/components/presenter-components.js
Currently, if the content cant fit on the screen you won't be able to see it because the notes don't scroll.
This fixes that
=> Allow presenter notes to scroll

example/src/index.js, src/components/appear.js
Fixed a bug where css was lost when applied to an element contained inside an <Appear /> tag.
Also added an example to show how one can use this new ability to layer fragments on top of each other with css.
=> Pass child css through to element wrapped in Appear tag

example/src/index.js, src/components/appear.js, src/components/slide.js, src/utils/step-counter.js
Hi
This PR implements step counter for `<Appear />` in `<Slide />`
To use simply add `getAppearStep` prop to `<Slide />` which is a callback and returns steps.
`<Slide ... getAppearStep={ steps => /* do something */ } /> `
Also added a slide to example.
Based on this branch https://github.com/pedrottimark/spectacle/tree/step-visitor
Use case can be like mine. I'm writing a presentation about ThreeJS and i have a canvas with renderer on slide background. On each step of text appearing i want to do something in ThreeJS.
I have a component with ThreeJS scene
`<CubeDemo step={this.state.cubeDemoStep} />`
And on each step i do something different in scene
```
animate() {
const delta = this.clock.getDelta();
if (this.step === 1) {
this.mesh.rotation.x += delta;
}
else if (this.step === 2) { …
```
=> Step counter feature

example/src/index.js, src/components/__snapshots__/image.test.js.snap, src/components/image.js
- Add max height & width to image element
- Updated Tests
- Builds off of PR #357
- Fixes #365 
- With large image:
* [Before](https://d28fz8geg24kjr.cloudfront.net/spectacle-large-before.png)
* [After](https://d28fz8geg24kjr.cloudfront.net/spectacle-large-after.png)
- Small Image:
* [Before](https://d28fz8geg24kjr.cloudfront.net/spectacle-kat-before.png)
* [After](https://d28fz8geg24kjr.cloudfront.net/spectacle-kat-after.png)
=> Fix large image slide cut-offs in presentation mode.

.eslintrc, .travis.yml, jest-setup.js, package.json, src/components/__snapshots__/block-quote.test.js.snap, src/components/__snapshots__/cite.test.js.snap, src/components/__snapshots__/code-pane.test.js.snap, src/components/__snapshots__/code.test.js.snap, src/components/__snapshots__/component-playground.test.js.snap, src/components/__snapshots__/controls.test.js.snap, src/components/__snapshots__/heading.test.js.snap, src/components/__snapshots__/image.test.js.snap, src/components/__snapshots__/link.test.js.snap, src/components/__snapshots__/list-item.test.js.snap, src/components/__snapshots__/manager.test.js.snap, src/components/__snapshots__/markdown-slides.test.js.snap, src/components/__snapshots__/presenter.test.js.snap, src/components/__snapshots__/progress.test.js.snap, src/components/__snapshots__/quote.test.js.snap, src/components/__snapshots__/s.test.js.snap, src/components/__snapshots__/table-header-item.test.js.snap, src/components/__snapshots__/table-item.test.js.snap, src/components/__snapshots__/table-row.test.js.snap, src/components/__snapshots__/table.test.js.snap, src/components/__snapshots__/text.test.js.snap, src/components/fullscreen.js, src/components/fullscreen.test.js, src/components/time-components.js, src/components/transitionable.test.js, yarn.lock
Bumps various dependencies for compatibility with React v16.0.0
resolves #364
=> Fix compatibility issues for React v16.0.0

README.md, src/components/__snapshots__/heading.test.js.snap, src/components/heading.js
Fixes this:
Also tested really quick in a fresh CRA / spectacle-scripts repo and the headings still rendered correctly.
Also a minor README spacing fix.
=> Fix React warnings for uppercase HTML heading elements

package.json, src/components/__snapshots__/manager.test.js.snap, src/components/manager.js
Removes the last piece of radium, manually implements global styles
=> Removes radium dep

README.md, example/src/index.js, src/components/slide.js, src/components/slide.test.js
=> Added support for enter and exit transitions.

README.md, src/components/markdown.js
Allows for prop based style overrides, cc @ryan-roemer
=> Fixes markdown styling

README.md, example/src/index.js, src/components/__snapshots__/manager.test.js.snap, src/components/manager.js, src/components/manager.test.js
I used a `Set` to track viewed indexes to ensure slides are only shown once. Indexes _are_ removed when we navigate backwards so slides can be re-shown. A viewed index ordered set is necessary to prevent an infinite loop. For example, if Slide 2 directs to 4, and Slide 4 directs to 3, when we go forward from 3, we want to go to 5, otherwise we will be stuck in a loop of 4 to 2, 2 to 3 to 4.
Addresses #375
=> Added out-of-order slide navigation.

README.md, docs/tag-api.md, index.html, one-page.html, package.json, src/components/__snapshots__/code-pane.test.js.snap, src/components/__snapshots__/component-playground.test.js.snap, src/components/code-pane.js, src/themes/default/print.js, src/themes/default/screen.js, src/utils/prism-import.js, src/utils/prismImport.js, yarn.lock
Fix #388 
- Remove all references to prism's CSS and CDN bundle from the readme
- Add prismjs package
- Use react-live's `1.8.0-1` i.e. `spectacletest` release which includes a `language` prop and externalised prism build
- Add `src/utils/prism-import` file (**This includes all syntaxes that we'll support out of the box**)
- Mirror ComponentPlayground theming and setup
- Rename theme properties
**Breaking Changes:**
- The `codePane` theme's properties have been changed to `wrapper` and `editor`. They could stay `pre` and `code`, but this wouldn't reflect the actual elements accurately.
**Future:**
It'd be great to add some instructions on how to add more prism components. The added text to the Readme is minimal but doesn't really say much.
It'd be great to make the playground and …
=> Bundle Prism and use react-live's Editor instead

README.md, example/src/index.js, src/components/__snapshots__/go-to-action.test.js.snap, src/components/go-to-action.js, src/components/go-to-action.test.js, src/components/manager.js, src/index.js, src/themes/default/screen.js
=> Add GoToSlide button

src/components/__snapshots__/component-playground.test.js.snap, src/components/component-playground.js
- Prevent passing invalid HTML attributes as props to emotion
- Stop propagation of key events in the Editor to be able to use all
keys
(Otherwise space, arrows, etc, would still change slides/modes)
=> Fix ComponentPlayground invalid props and key events

package.json, src/components/__snapshots__/code-pane.test.js.snap, src/components/__snapshots__/component-playground.test.js.snap, src/components/__snapshots__/fullscreen.test.js.snap, src/components/__snapshots__/manager.test.js.snap, src/components/code-pane.js, src/components/component-playground.js, src/components/fullscreen-button.js, src/components/fullscreen.js, src/components/fullscreen.test.js, src/utils/fullscreen.js, yarn.lock
Fix #316 
Depends on #391 
Adds a fullscreen button to the `ComponentPlayground` that uses the Fullscreen API.
=> Add fullscreen button to ComponentPlayground

README.md, example/src/index.js, src/components/slide.js, src/components/slide.test.js
=> Added support for a slide onActive function prop

package.json, src/components/markdown.js, yarn.lock
=> Upgraded Marksy, styles now showing.

README.md, src/components/appear.js, src/components/slide.js, src/components/slide.test.js
=> Added <Appear /> order prop.

src/components/__snapshots__/manager.test.js.snap, src/components/__snapshots__/presenter.test.js.snap, src/components/export.js, src/components/presenter.js
=> Avoid in/out transitions in export and presenter modes

example/src/index.js, src/components/manager.js
=> Fixed issues with slide indexing for synced tabs and out-of-order indexing

README.md, example/src/index.js, src/components/__snapshots__/image.test.js.snap, src/components/__snapshots__/manager.test.js.snap, src/components/__snapshots__/progress.test.js.snap, src/components/controls.js, src/components/image.js, src/components/manager.js, src/components/progress.js, src/themes/default/screen.js
This adds the props `controlColor` and `progressColor` to the Slide tag, adding the ability to override the colors for control arrows and progress elements on a per slide basis.
Also updates docs for this feature, updates the docs for some missing props, and adds the `alt` attr to the Image element.
Fixes #420
=> Progress updates

src/utils/magic.js
This fixes 2 things:
- Takes into account the positioning of the parent elements
- Repurposes already prism-wrapped copy inside of spans
=> Fixes #422 (Magic Move)

example/src/index.js, package.json, src/components/__snapshots__/markdown.test.js.snap, src/components/code.js, src/components/markdown.js, src/components/markdown.test.js, yarn.lock
Created a test case for it. You can see in the snapshot that a `CodePane` is produce, which should be a `Code` element.
Both the `Code` and `CodePane` elements work strangely when produced by the Markdown output. Besides this, correctly formatted `CodePane` elements are only highlighted if the slide is focused on page load. Switching into a Slide with a `CodePane` generated by Markdown leaves the `CodePane` unhighlighted. Pretty strange.
This was also an issue in Spectacle 2.* (which I was using previously). I'm in the process of upgrading to 4.0, which also means converting the Markdown slides into React ones, because I keep running into this issue and need more control over the styles.
I'm opening this PR to get some thoughts as to why these things may be happening and where I should …
=> Inline code w/ markdown produces a `CodePane`, not `Code`

package.json, yarn.lock
As filled in #447.
A dependency of spectacle did had two security vulnerabilities, CVE-2017-17461 and CVE-2017-1000427.
The yarn.lock file enforced to install a lower version in development so I did upgrade this one. 
There has not been any breaking change in dependencies of the marksy package or marksy itself.
=> Update marksy to 6.0.2 for CVE-2017-17461 and CVE-2017-1000427

package.json
This adds a link on the npm package page:
https://www.npmjs.com/package/spectacle
which is currently missing.
=> ADD a repository field on package.json

README.md, src/components/__snapshots__/code-pane.test.js.snap, src/components/__snapshots__/component-playground.test.js.snap, src/components/code-pane.js, src/components/component-playground.js
Fix #458
When applied this PR 'hides' our built-in Prism themes behind the `.builtin-prism-theme` class, which is applied by default. It can be disabled by setting the `theme` prop to `"external"` which allows external themes to style Prism in whatever way they'd like.
This also adds a stricter prop-types check for the theme prop, and passes on the correct `language-X` class for Prism. (Quick on-the-side-fix)
A user might still run into specificity problems where themes can mix when their own Prism theme contains some really generic selectors with a higher specificity than ours. I don't think there's any value in preventing this with even more specific selectors on our end, instead the README now just mentions this.
~Edit: not quite sure why, but an unrelated snapshot changed as well. …
=> Add `theme="external"` to disable the built-in prism themes

README.md
Previously, the browser treated `github.com/emotion-js/emotion` as a relative link. Specifying `https://` gives the browser a full URL so it correctly navigates to the Emotion repository.
=> Add protocol to emotion link

src/components/component-playground.js
`LiveProvider` uses Buble to transform code, but that only supports ES2015, and not newer syntax like Class Properties.  
`LiveProvider` accepts a `transformCode` prop that can be used as an alternative to the built-in transformation, but Spectacle's `ComponentPlayground` doesn't expose that.  By passing `transformCode` through, end users can customize the compilation process (such as using `babel-standalone` instead of Buble).
I've got some code samples that use Class Properties, and they worked on older versions of Spectacle.  I hand-edited my local copy of Spectacle to expose the `transformCode` prop, and was able to successfully compile the code using `babel-standalone`.  I'd like to get this merged in and published.
=> Expose LiveProvider's transformCode prop

src/components/__snapshots__/component-playground.test.js.snap, src/components/__snapshots__/fullscreen.test.js.snap, src/components/__snapshots__/manager.test.js.snap, src/components/fullscreen-button.js
Adds an `aria-label` to the fullscreen button so that screen reader users can tell what it is.
=> Add aria-label to fullscreen button

README.md
- Added sentence warning users not to use the `transition` prop w/ Magic Move (I learned this the hard way 😅 )
=> [docs] Warns users not to use a transition prop w/ Magic Move

README.md, example/src/index.js, src/components/anim.js, src/components/appear.js, src/components/manager.js, src/components/slide.js, src/components/slide.test.js, src/index.js, src/reducers/fragment.js, src/utils/step-counter.js, src/utils/types.js
**Hi again Formidable folks 👋!** Really loving my time with spectacle, it's super fun to work with and a nice change of pace from reveal.js. Super appreciate all the work y'all've done on it and the opportunity to contribute to the project.
I'm using Spectacle to make a deck for a talk on web animation, so I wanted some more flexibility animating fragments. Specifically I wanted to be able to animate a fragment multiple times before moving on to the next fragment or slide.  I ended up more-or-less replacing the `<Appear>` component with a more generalized `<Anim>` component, creating a simpler `<Appear>` component which is just a wrapper for `<Anim>` to avoid shipping any breaking changes, and made a few small alterations in `<Slide>` and `<Manager>` to accommodate the ability to step …
=> Flexible <Anim> component

package.json, yarn.lock
Fix https://github.com/FormidableLabs/spectacle/issues/512
cc @kenwheeler
=> Pin prismjs version to 1.6.0

src/components/heading.js
Got a quite cryptic error:
```
Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.
You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports. Check the render method of `Heading`.
```
Took me a while to realize, that I tried to use a `Heading` with `size` `7`.  The proposed error is more obvious to me.
=> Throw error if heading size is higher than 6

package.json, src/components/__snapshots__/code-pane.test.js.snap, src/components/__snapshots__/component-playground.test.js.snap, yarn.lock
Prism was nailed down to 1.6.0 due to https://github.com/FormidableLabs/spectacle/issues/512, but spectacle still depends on `react-live` which has a dependency on Prism 1.14.0
```
│ │ ├─┬ react-live@1.10.1
│ │ │ ├─┬ buble@0.19.3
│ │ │ │ ├── acorn@5.6.2 deduped
│ │ │ │ ├─┬ acorn-dynamic-import@3.0.0
│ │ │ │ │ └── acorn@5.6.2 deduped
│ │ │ │ ├─┬ acorn-jsx@4.1.1
│ │ │ │ │ └── acorn@5.6.2 deduped
│ │ │ │ ├─┬ chalk@2.4.1
│ │ │ │ │ ├── ansi-styles@3.2.1 deduped
│ │ │ │ │ ├── escape-string-regexp@1.0.5 deduped
│ │ │ │ │ └─┬ supports-color@5.4.0
│ │ │ │ │   └── has-flag@3.0.0
│ │ │ │ ├─┬ magic-string@0.22.5
│ │ │ │ │ └── vlq@0.2.3
│ │ │ │ ├── minimist@1.2.0 deduped
│ │ │ │ ├── os-homedir@1.0.2 deduped
│ │ │ │ └── vlq@1.0.0
│ │ │ ├── core-js@2.5.7 deduped
│ │ │ ├─┬ dom-iterator@1.0.0
│ │ │ │ ├── …
```
=> Prism version conflict

src/components/component-playground.js
This is important for ensuring that transitions on a slide with a Component Playground don't cause the previewed component to get recreated/remounted.
=> Memoize component playground scope.

src/components/__snapshots__/link.test.js.snap, src/components/link.js
__changes__
This PR is for adding `rel="noopener noreferrer"` into `<a>` when its target is `_blank`.
Also, I changed `<Link>`'s propTypes. so that `target` can be one of `_blank`, `_self`, `_parent`, `_top`.
__references__
- [Opens External Anchors Using rel="noopener"](https://developers.google.com/web/tools/lighthouse/audits/noopener)
- [Html/Elements/a](https://www.w3.org/wiki/Html/Elements/a)
- [Reverse Tabnabbing](https://www.owasp.org/index.php/Reverse_Tabnabbing)
=> add rel attribute into Link to prevent tabnabbing attack

src/components/slide-components.js
Fixes an issue originally raised in outdated PR #517 where since `0` is a falsey value, it wasn't properly being applied when specified by the user, and was reverting to the default of `40`.
=> Allow Slide Margin of 0

src/components/__snapshots__/fullscreen.test.js.snap, src/components/__snapshots__/manager.test.js.snap, src/components/fullscreen-button.js, src/components/fullscreen.js, src/themes/default/screen.js
This updates how color is passed to the fullscreen button - if no color is specified in a theme, it remains white, or default, but otherwise it should take on the color specified. Fixes #563
=> Fullscreen Button Takes Applied Color

src/components/anim.js
Fixes #540 
- Replaces deprecated componentWillReceiveProps according to [docs](https://reactjs.org/docs/react-component.html#unsafe_componentwillreceiveprops)
=> Replace componentWillReceiveProps with componentDidUpdate

src/components/anim.js
A change from `componentWillReceiveProps` to `componentDidUpdate` had some problematic `setState`s. This fixes the issue by extracting the `setState`s into separate methods and adding additional catch logic.
=> Fix Issue with Repeated Set State in ComponentDidUpdate

.github/PULL_REQUEST_TEMPLATE.md, .github/issues/bug_report.md, .github/issues/feature_request.md
Reintroduces github templates that were accidentally wiped out with a prior commit. 🙂
=> Add `.github` dir with templates

src/components/component-playground.js, src/components/heading.js, src/components/magic-wrapper.js, src/components/manager.js, src/components/notes.js, src/components/text.js
=> [WIP] Remove deprecated lifecycles

README.md, src/components/appear.js
`Appear` can only have one child to behave correctly which caused issue #597. `CodePane` has a child of its own. When it is inside an `Appear` tag it changes the slide index...
```
Slide with index of 0
Slide with index of 1(Slide with an `CodePane` inside an `Appear` tag)
Slide with index of 2
```
to
```
Slide with index of 0
Slide with index of 1
Slide with index of 0
Slide with index of 1
Slide with index of 2
```
Updated Readme docs to reflect this.
Fixes # 597
Test with a simple app
=> add div to surround Appear tag children

README.md
=> add docs about spectacle mdx

src/components/__snapshots__/manager.test.js.snap, src/components/manager.js, src/components/overview.js
Fixes #559 by resetting viewed items when the user navigates to a slide using the overview feature.
Reproduced the issue using the example deck and the steps outlined in #559, tested manually after making the fix.
~~- [ ] I have added tests that prove my fix is effective or that my feature works~~ ***I've updated snapshots to make sure the right props are being passed through, but there are no tests for the Overview component at the moment.***
~~- [ ] I have commented my code, particularly in hard-to-understand areas~~
~~- [ ] I have made corresponding changes to the documentation~~
~~- [ ] Any dependent changes have been merged and published in downstream modules~~
=> Fix slide navigation after coming out of overview mode

package.json, src/components/heading.js, yarn.lock
This PR fixes the broken `start` script in a fresh clone of Spectacle. It also cleans up one instance of `componentDidMount` appearing before `getDerivedStateFromProps` to satisfy lint, which should no longer be outputting any errs.
Run `npm run clean`, `npm run build:dist`, and then `npm start`. Navigate to [http://localhost:3000](http://localhost:3000) to confirm the sample slideshow has been built and is being output into the browser.
Run `npm run lint` to confirm there are no more lint errs.
=> Update some packages to fix `yarn start`

src/components/manager.js
```js
export default class Presentation extends React.Component {
render() {
return (
<Deck>
<Slide>
<Text>Test slide</Text>
</Slide>
</Deck>
);
}
}
```
Single `<Slide />` decks currently crash the app. This adds a couple guards so we can render this.
=> Fix single slide decks

src/components/appear.js
The default props for `<Appear />` makes untransitioned elements invisible, but they still register pointer-events (e.g., a `<Link />`). This just adds `pointerEvents: "none"` to the starting state so invisible elements do not register clicks.
Fixes #397 
Manually through spectacle-boiler-plate.
```jsx
export default class Presentation extends React.Component {
render() {
return (
<Deck
showFullscreenControl={true}
transition={["zoom", "slide"]}
transitionDuration={500}
>
<Slide
transition={["slide"]}
bgImage={
"https://cdn.rawgit.com/FormidableLabs/spectacle/master/example/assets/city.jpg"
}
bgDarken={0.75}
>
<Appear fid="1">
<Heading size={1} caps fit textColor="primary">
Test Slide
</Heading>
</Appear>
<Appear fid="2">
<Link
href="#link" …
```
=> Make sure hidden <Appear />s ignore mouse events

CONTRIBUTING.md, README.md
Rel https://github.com/DefinitelyTyped/DefinitelyTyped/pull/31744 and #630, we want our docs to point to the local type definitions instead of the now-removed DefinitelyTyped file.
Installation steps were tested manually with a sample TypeScript presentation.
=> Update docs to reference local type definitions

docs/tag-api.md
Updated PropTypes definition in documentation
=> Update `React.PropTypes` to `PropTypes`

.npmignore
Typescript type definitions were excluded from the built package via`.npmignore`. This PR adds an exception for the file so that the type definitions are installed correctly.
Fixes #646
Ran `npm pack && tar --list --file spectacle-5.3.0.tgz | grep index.d.ts` to verify that the `index.d.ts` file is included in the tarball.
=> Include index.d.ts in package

README.md, example/src/index.js, src/components/__snapshots__/list-item.test.js.snap, src/components/list-item.js, src/components/list.js, src/components/list.test.js, src/utils/base.js
This feature allows adding custom bullets to `List` and `ListItem` elements. If the `bulletStyle` prop is passed to `List` component it changes the default enumerators styling for all `List` elements unless `bulletStyle` prop for `ListItem` is passed at the same time, which overwrites the styling of the parent element for particular `ListItem` only.
The user can either pass any Unicode number or use a few pre-defined strings to execute the new styling.
Fixes #437
=> Custom listItem enumerators with unicode

README.md
This PR clears up the query param prefix in our docs. We weren't very explicit about including the hashroute when using those query params, now we are.
Rel [this tweet](https://twitter.com/k1sul1/status/1101124868060446722), kind of.
=> Update docs to include hashroute for query parameters

src/utils/controller.js
This change fixes the following warning raised by ``history`` in the browsers :
```
Warning: Please use `require("history").createHashHistory` instead of `require("history/createHashHistory")`. Support for the latter will be removed in the next major release.
```
=> Fix: ``createHashHistory`` import syntax

README.md, example/src/index.js, src/components/slide.js, src/utils/slides.js
This allows to apply styles over all children of `SlideSet`
Fixes #587 
- Added the use case to example.
- do `yarn run start` and open http://localhost:3000/#/ to try out the example
=> apply styles to child in SlideSet

README.md
Add a link to the live demo deck at the top of the README file. 
Fixes Issue #671, user requested a link to a live demo to quickly see what Spectacle looks like and is capable of. 
Ran prettier and linter, no other tests performed as this is only an update to the docs.
=> add live demo link to readme

README.md, one-page.html
- Fixes CSSStyleDeclaration index property setter error.
- Runs prettier on `one-page.html`, too.
Loosely relates to issue #55 - primarily the last comment on there (from @ebello on 17 Apr)
I feel the original bug in that issue has likely been resolved by the latest version (not directly confirmed), but the issue raised in the comment is fixed by this.
Bug fix (non-breaking change which fixes an issue)
Tried `one-page.html` before and after: 
- Before, the error occurs on `one-page.html#/12` on Chrome 74\* & Firefox 67\*\*
- Error doesn't occur on Safari
- After, the error doesn't occur on any slide on Chrome, Firefox, Safari.
- Works fine with both the `one-page.js` from versions `^4` and `^5` as they are identical, but have updated this to version 5 for consistency
\* Error: `TypeError: …
=> Update one-page.html to use spectacle 5

examples/JS/TestJS.js, index.js, src/components/Deck.js, src/components/Slide.js, src/utils/isComponentType.js
- Add `TestJS` example
- Add TestJS to root `index.js` where we're testing rendering these files. Kept `MDXDocument` in so we can switch easily for now
- See note added to `Deck` `map`
=> Add example using JS rather than just MDX

index.d.ts
The docs call for a number but strings (i.e. 95vw) seem to work fine.  #361 suggested a problem but that code doesn't seem to exist anymore.
manually checked that it worked
=> Add contentWidth and contentHeight to DeckProps

CONTRIBUTING.md, index.d.ts
Rel #312 - adds these new types to the type defs
=> Add bulletStyle types

src/components/manager.js
This PR is a one liner fix for the Issue #685. This line of code (758 in `Manager.js`) was wrong
```
(slide.props.transition || {}).transitionDuration
```
`slide.props.transition` is of type array so this is always `undefined`.
Fixes #685 
I added a `transitionDuration` prop to `example/src/index.js` and checked that it worked locally.
I'm not sure how to add tests for this. I could do something like... …
=> Fix transitionDuration prop for Slide component

examples/js/test-js.js, src/components/code-pane.js
Previously the Code Slide would cause longer lines of code to go out of bounds on the screen forcing a horizontal scroll. Now we wrap it like an IDE.
*How it used to look*
We also add line numbers and support both dark and light themes using transparent backgrounds and lines. The line numbers use the foreground color of the default text in the theme, so there should be no color collisions.
This also fixes the default fonts for each platform and removes the Google Font feature. To get the correct calculation using Canvas Context, the fonts need to exist on the system. Code Panel will now support any _installed_ font and have fallbacks for common monospace fonts on macOS and Windows.
We calculate the size of the spaces for indentation and trim whitespace. This lets us pad the entire line so …
=> Fix margin overflow, add line numbers

bin/actions.js, bin/args.js, bin/cli.js, bin/validate/presentation-mode.js, mdx-slides/index.js, src/components/deck/index.js, src/components/deck/presenter-deck.js, src/theme/index.js
This PR introduces the ability to override the default theme when starting a presentation from the CLI. The user can override portions or all of the default theme. **The theme file must be a JavaScript file.**
To understand how to override the theme, first look at the default theme: https://github.com/FormidableLabs/spectacle/blob/task/rewrite/src/theme/default-theme.js.
Notice that there are categories within the theme, e.g. `colors`, `space`, etc. Your theme override JS file must follow the same structure. If you want to override the secondary color and header margin, then your theme file would look like this:
```
export default {
colors: {
secondary: 'blue',
},
space: {
headerMargin: '30px 20px',
}
};
```
1. ensure that spectacle is linked (`npm link` from the root of spectacle …
=> Override theme via CLI

bin/actions.js, src/theme/backup-user-theme.js, src/theme/index.js
Instead of try/catch-ing a faulty alias for user-supplied theme, this PR provides a backup file for the alias. Test it the same way you might test [this PR](https://github.com/FormidableLabs/spectacle/pull/727).
=> better solution for aliasing user theme

bin/actions.js, package.json, src/theme/backup-user-theme.js, webpack.config.js
Fixes the use theme alias for JSX-mode. Confirmed still works for MDX/CLI-mode!
=> Add Alias for default theme when none is supplied in JSX mode

src/components/deck/index.js, src/components/deck/overview-deck.js, src/components/fullscreen.js, src/components/progress.js, src/hooks/use-deck.js, src/hooks/use-url-routing.js
Add support for Overview mode via a URL query param.
`overviewMode=true` gives you a grid layout of all of your slides. We disable individual control on the slides and clicking on one takes you to that slide in regular mode.
=> Add support for Overview-mode

README.md
Adds a link to my repo that demonstrates a method of creating slide
templates. As explained on the original issue, this could change
entirely when the Spectacle API changes, but for now it's good to have
documented.
Closes #655
I haven't tried this since originally having worked on it with the
Spectacle release that was available at the time, but if comments on the
issue are anything to go by, it's still up to scratch. I may have the
time to do this at some point if necessary.
=> Document creating slide templates

examples/js/test-js.js, examples/one-page.html, package.json, src/components/deck/index.js, src/components/markdown.js, src/index.js, src/utils/indent-normalizer.js
Adds new Markdown Component to Spectacle
The new Markdown component can either be used to add content within a slide or be used top-level under `<Deck />` to add 1...n slides using the `---` delimiter. 
Example Usages:
```jsx
<Deck>
<Slide>
<Markdown>
{`
- Yes you are!
\`\`\`js
fields @timestamp, res.duration
| filter res.duration > 0
| sort @timestamp desc
| limit 20
| stats min(res.duration), avg(res.duration), max(res.duration) by bin(30m)
\`\`\`
`}
</Markdown>
</Slide>
<Markdown containsSlides>
{`
---
`}
</Markdown>
</Deck>
```
Tested in regular, overview, and presentation modes:
=> Added new Markdown Component

src/components/__snapshots__/table-header-item.test.js.snap, src/components/table-header-item.js
Fixes #743 by using `th` for the TableHeader component instead of `td`
Snapshots have been updated to match the new element rendered, but nothing else changed 🙂
=> Use th for TableHeader

examples/js/test-js.js, src/components/code-pane.js, src/components/markdown.js, src/components/slide.js, src/components/typography.js, src/hooks/use-autofill-height.js, src/theme/default-theme.js, src/utils/mdx-component-mapper.js
The idea is to allow for CodePane to consume the empty space around the footer and elements automatically with an opt-in prop. Prior, the user would have to either calculate or best-guess the max-height value to do so. This applies for CodePanes with lots of content. This full-height calculation can be extended to other components down the road.
=> Add base JS-based auto sizing

.prettierignore, examples/js/test-js.js, examples/one-page.html, src/components/typography.js, src/index.js, src/theme/backup-user-theme.js, src/utils/mdx-component-mapper.js
Markdown example to demonstratte indentation problem with prettier and marksy.
In this [case](https://github.com/FormidableLabs/spectacle/pull/746/files#diff-27d1398137d07ae13f238fccada6a73fR90-R101) marksy interprets the code as a codepane, not a table. After having it explained by Carlos, this makes sense but this is probably a sub-optimal user experience and we should think about how to solve this.
=> Table component branch bug

examples/one-page.html, src/components/deck/index.js, src/theme/backup-user-theme.js, src/theme/index.js, webpack.config.js
As discussed internally, we don't need to webpack alias a made up `spectacle-user-theme` thing to allow user-provided theme overrides via manual `Deck` or the CLI. We can just pass them as props to the top level exported deck and much more simply have it all work out.
Work:
- Removed unneeded files and webpack alias.
- Add override example in `one-page.html`
Example:
```js
<Deck
theme={{
colors: {
secondary: 'yellow'
}
}}
>
<Slide>
```
To test out:
```sh
$ git checkout chore/remove-theme-alias
$ yarn build
$ open examples/one-page.html
```
You should see a pink heading (colored `secondary`) on the first page instead of default theme color. Try out other theme overrides in `examples/one-page.html` and refresh to see in action!
=> Remove spectacle-user-theme webpack alias strategy.

src/components/deck/index.js, src/components/fullscreen.js, src/hooks/use-deck.js, src/hooks/use-full-screen.js, src/hooks/use-keyboard-controls.js, src/hooks/use-url-routing.js, src/utils/detect-platform.js
This branch provides feature parity with existing spectacle for the keybindings for setting specific modes. 
Alt + P -> Presenter mode.
Alt + O -> Overview mode.
Alt + F -> Fullscreen mode. 
https://github.com/FormidableLabs/spectacle#controls
=> keyboardControls

examples/js/index.js, package.json, src/components/deck/index.js, src/index.js, src/utils/notes.js, yarn.lock
Support Notes for the Markdown Slides Component
```jsx
<Markdown containsSlides>
{`
Notes: These are notes
---
Notes: These are more notes
`}
</Markdown>
```
=> Support Notes for MD parsing

src/components/deck/index.js, src/utils/is-component-type.js, src/utils/search-children-appear.js
Check `Component.name` instead of `'Component'` string as the `name` field is subject to mutation by minification.
Fixes #763 
Validate with a static example in production mode:
```sh
$ yarn build-webpack-examples-js --mode production
$ npx serve examples/js/dist/
```
Navigate to http://127.0.0.1:5000/?slide=0&slideElement=0
Should now have a working presentation page.
=> Bug: Check component name field, not string.

README.md
If my guess is right, 'inconstiency' is misspelled of 'inconsistency'. 
=> fix 'inconsistency' spelling in README

.travis.yml, README.md
- Add minor comments and documentation live link.
- **Netlify**: We have a `spectacle` Netlify user in 1password now and a configured site. We deploy the JS examples `examples/js/dist` as our "website".
- **GitHub**: We have a new `spectacle-ci` GH user in 1password as well for Netlify integration.
- This PR should (hopefully 🤞 ) do a preview deploy then real one to https://spectacle.formidable.com once we merge.
- Netlify currently is configured to deploy on `task/rewrite` branch. After release, we'll switch to `master`. #777
/cc @kale-stew @boygirl @carlos-kelly
=> Infra: deploy spectacle demo!

README.md, src/components/deck/index.js, src/components/progress.test.js, src/components/slide.js, src/components/table.test.js, src/components/typography.test.js, src/hooks/use-autofill-height.js
The goal is to enable a quick way to enable flex to allow for content to be center positioned in the slide and flex column. This should allow for quicker layout when not wanting to use Box/Flex/Grid components or when using MDX.
This prop does two things
1. Makes the template and slide content flex siblings since you cannot control the template overlapping in MDX mode
2. Center-positions the slide content vertically using flex
Example showing the layout margins of the flex siblings of slide content and template:
=> Added support for flex-based AutoLayout

examples/js/index.js, src/components/__snapshots__/table.test.js.snap, src/components/table.js
Prior Tables did not have full-width and the list in the demo needed extra line breaks for the parser.
=> Fix Table and Lists

.travis.yml, docs/scripts/deploy/aws.js
Part of #793
- Upload **for reals** to `open-source/spectacle-TODO-TESTING` production site (but a non-linked directory).
Files should go there but the web app may not correctly work because the url path won't match what it was built against.
/cc @boygirl @kale-stew @carlos-kelly
=> Infra: Do real deploy to temp directory.

.gitignore, docs/content/tutorial.md, docs/scripts/deploy/aws.js, docs/src/screens/docs/sidebar.js
- Deploy to production for real! Part of #793 
- Fix slug headers. Fixes #794
Here's the planned production changes:
```
(dryrun) upload: dist/404.html to s3://formidable.com/open-source/spectacle/404.html
(dryrun) upload: dist/404/routeInfo.json to s3://formidable.com/open-source/spectacle/404/routeInfo.json
(dryrun) delete: s3://formidable.com/open-source/spectacle/bootstrap.9d3fd336.js
(dryrun) upload: dist/bootstrap.e8eb35db.js to s3://formidable.com/open-source/spectacle/bootstrap.e8eb35db.js
(dryrun) upload: dist/client-stats.json to s3://formidable.com/open-source/spectacle/client-stats.json
(dryrun) delete: s3://formidable.com/open-source/spectacle/docs/base-props/index.html
(dryrun) delete: s3://formidable.com/open-source/spectacle/docs/base-props/routeInfo.json
(dryrun) upload: …
```
=> Infra: Deploy to prod! (And minor fixes).

docs/content/api-reference.md, src/components/layout.js
- Add layout, code pane, progress, and deck template docs
- Add color props support to Flex Box
=> Layout and Component Docs

CHANGELOG.md, src/components/fullscreen.js, src/components/slide.js, src/hooks/use-full-screen.js
- Fixes zIndex issue which broke the full screen button on the example template
- Adds support for full screen in Safari
#834
=> Fixed Full Screen

docs/content/getting-started.md
A relative path in a link to `tutorial.md` from `getting-started.md` was wrong, which resulted in a dead link to the tutorial.
I clicked the link in preview mode, and it works now. :)
=> fix tutorial markdown link mismatch

docs/src/screens/docs/sidebar.js
@carlos-kelly @kale-stew 
This PR replaces the link to `docs/getting-started` (which doesn't exist as a route in this app) with a link to `/docs`. This PR also removes ampersands from sidebar links so that they match the anchor ids generated when we parse the markdown. Prior to this change, clicking on `build & deployment` in the sidebar would not correctly scroll the page.
=> fix sidebar naming

CONTRIBUTING.md, docs/content/advanced-concepts.md, docs/content/api-reference.md, docs/content/basic-concepts.md, docs/content/extensions.md, docs/content/faq.md, docs/content/themes.md, docs/content/tutorial.md, docs/src/screens/docs/sidebar.js, examples/md/slides.md
This PR consolidates efforts to introduce a tutorial (thanks for your work on [`task/tutorial`](https://github.com/FormidableLabs/spectacle/blob/de3b6f62cd4f80103acfb307a29de3cb635e7929/docs/tutorial.md), @carlos-kelly) and guts more TODOs preparing for release.
Remaining tasks:
**Upcoming PR:**
```md
```
=> Docs: Add tutorial

examples/js/index.js, examples/one-page.html, src/index.js, src/utils/indent-normalizer.test.js
- Export `indentNormalizer` for manual use.
- Add `indentNormalizer` unit tests.
- Update examples/js and examples/one-page. Fixes #846 
- Looks like `yarn build-one-page` also needed running to catch up.
=> BUG: Fix indent in C++ example in one-page.

docs/content/api-reference.md, examples/js/index.js, examples/one-page.html, index.d.ts, src/components/code-pane.js, src/components/deck/index.js, src/components/stepper.js, src/index.js, src/utils/search-children-appear.js, src/utils/search-children-stepper.js, src/utils/search-children-stepper.test.js
This adds code range highlighting/stepper support, similar to [this project](https://github.com/jamiebuilds/spectacle-code-slide).
Added tests for the `searchChildrenForStepper` util, which is handling most of the logic.
=> Add code range highlighting and stepping

CHANGELOG.md, docs/content/api-reference.md, docs/content/props.md, examples/js/index.js, examples/one-page.html, index.d.ts, src/components/deck/presenter-deck.js, src/components/slide.js
Expands custom background support by adding [`Background`](https://styled-system.com/api#background) props to the `Slide` component, along with `backgroundOpacity`.
Added an [example slide](http://localhost:3000/?slide=2)
=> Expand slide background support

src/components/deck/presenter-deck.js
Fixes an issue with notes overlapping in presenter view. (See image below for bug)
=> Remove lineHeight unit from notes text

.travis.yml, CONTRIBUTING.md, README.md, docs/content/basic-concepts.md
Points all links from `task/rewrite` to `master` where applicable. This _should_ be the final PR to our rewrite branch before it's released.
Closes #777
=> Point docs to master branch

docs/content/api-reference.md
=> Add docs for table

docs/content/extensions.md
I fixed a broken link found here:
https://github.com/FormidableLabs/spectacle/blob/master/docs/content/extensions.md
From: https://github.com/FormidableLabs/spectacle/releases/tag/v6
To: https://github.com/FormidableLabs/spectacle/releases/tag/v6.0.0
- Small typo fix
I ran the docs locally and ensured the link resolved to the correct destination.
=> fix broken link in extensions.md documentation

src/components/typography.js
Style System's library doesn't include the key 'textDecoration'. It has to be added manually so it can be changed through the theme. This is useful to remove the underline of links. I followed the instructions here: https://styled-system.com/custom-props
I created a presentation and include a slide with a Link, trying to remove the underline from it:
`<Link textDecoration='none'>Testing</Link>`
=> Add custom style prop 'textDecoration' to Link

CHANGELOG.md, src/components/code-pane.js
Fixes #874 -- now, users can provide a `fontSize` prop to CodePane to dynamically change the font. It will look for props first, then for a monospace theme, and finally fall back to the default size of `15px`.
=> Allow for dynamically updated fontSizes in CodePane

src/components/deck/index.js, src/hooks/use-touch-controls.js
On mobile devices, without keyboard, it was impossible to move through the presentations. Users would expect being able to swipe left or right to advance and go back.
I copied the way `use-keyboard-controls.js` handled it, replacing the keyboard with touch events.
On browsers without touch capabilities, the events never fire, so having the hooks should not change anything.
I ran the development server and tested on both my desktop and mobile devices, using the example presentations.
=> Added touch controls to navigate presentations

docs/content/advanced-concepts.md, docs/content/basic-concepts.md, docs/content/faq.md, docs/content/index.md
Replace `?export` with new `?exportMode=true` across docs.
Checked markdown preview in `vscode`.
=> Fix docs, replace ?export with ?exporterMode

src/hooks/use-keyboard-controls.js
Pull request to address the issue of keyboard shortcuts not working for Mac. I also discovered that the shortcuts weren't working for Windows as well.
Fixes #888 
The conditions for keyboard shortcuts for Windows & Mac were always falsy, unless CAPS lock was enabled. Tested locally on Windows, **however please test additionally for Mac machines** before merging.
=> ALT-O Keyboard shortcut fix. Issue: #888

docs/src/screens/home/_content.js
This PR just fixes the description of `renature` on the Spectacle docs site 🤗 
I cloned the repo and ran the docs site at `localhost:3000/open-source/spectacle`. The `renature` entry now has the proper description that matches its own docs site:
While I was here I noticed that the badges in the footer don't appear to be of uniform size (see screenshot above) 🤔 Just a call out for an additional update if someone else wants to take this on!
=> Fix description of renature on docs site.

CHANGELOG.md, examples/one-page.html, src/hooks/use-keyboard-controls.js, src/hooks/use-keyboard-controls.test.js, src/utils/detect-platform.js
Keyboard controls only work for Windows and Mac.
I am using an Ubuntu and when I start my presentation and press one of the following combinations nothing happens.
`Alt` + `O`
`Alt` + `P`
`Alt` + `F`
Fixes #904 
`yarn`
`yarn check-ci`
`yarn test`
`yarn build` + tested it locally
`yarn format`
=> Add hotkeys support on linux.

CHANGELOG.md, docs/content/api-reference.md, index.d.ts, src/components/code-pane.js
This PR allows for an `indentSize` prop to be supplied to the CodePane. Feedback welcome!
=> Allow for larger indentation in the CodePane

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/question.md, .github/PULL_REQUEST_TEMPLATE.md, .travis.yml, CONTRIBUTING.md, README.md, docs/README.md, docs/content/api-reference.md, docs/content/basic-concepts.md, docs/content/faq.md, docs/content/index.md, docs/content/tutorial.md, docs/src/screens/home/_content.js, examples/js/index.js, examples/one-page.html
This PR updates references to the default branch for a number of Formidable repos, pending a few related merges.
- spectacle
- spectacle-cli － (rel [spectacle-cli#34](https://github.com/FormidableLabs/spectacle-cli/pull/34)) 
- spectacle-mdx-loader － (rel [spectacle-mdx-loader#7](https://github.com/FormidableLabs/spectacle-mdx-loader/pull/7))
- formidadogs － (rel [dogs#16](https://github.com/FormidableLabs/dogs/pull/16))
=> Update the default branch's name

src/components/deck/presenter-deck.js, src/components/deck/presenter-deck.test.js, src/components/slide.js, src/hooks/use-slide.js, src/hooks/use-url-routing.js
Fixes #914
Tested with `start:js`, presenter view now properly shows the preview of the next animation.
=> Presenter mode should show the next animation rather than the next slide

src/components/deck/deck.js, src/components/deck/index.js
- Adds support for `overviewMode=true` or `presenterMode=true` to set the deck style into those modes.
- Supports ignoring the param if the value is `false`.
=> Support presenter and overview mode query params inside the url.

package.json
Bumps Babel version numbers which allows for functional building on Windows CMD/PowerShell
=> v7: Bump version number for Babel to build on Windows

src/components/deck/deck.js, src/components/deck/default-deck.js, src/components/deck/index.js, src/components/slide/slide.js, src/hooks/use-deck-state.js, src/utils/constants.js
1. Update the `slideIndex` value in the url `?slideIndex=2&stepIndex=0` in overview mode after a user presses the **tab** key to select a certain slide or  **shift+tab** to select a previous slide
2. When user switches to overview mode, the current slide will have a outline white border applied to its div
3. Added outline style on hovering a slide in overview mode
4. Pressing enter or clicking on a slide in overview mode, will update the url to contain that slideIndex and exit overview mode
• To test PR, visit `http://localhost:3000/?slideIndex=3&stepIndex=0` with a `slideIndex` value of any slide, then press `ctrl/cmd + o` to switch over to overview mode
=> V7: Overview Mode | Update the slideIndex value in url after a user presses tab to select a slide

src/components/code-pane.js
After verifying that issue #918 was fixed in `main-7`, it was recommended by @carlos-kelly to also allow the user to pass a single array range `[3, 5]` to the `highlightRange` prop in Code Pane
To reproduce, pass the following values to the `highlightRanges` prop:
```js
highlightRanges={[6, 8]}
```
```js
highlightRanges={[
[1], 
[3], 
[6, 8]
]}
```
```js
highlightRanges={[
1, 
3, 
5, 
[6, 8]
]}
```
=> v7: Code Pane | Allow single array range in highlightRanges prop

src/components/deck/deck-styles.js, src/components/deck/deck.js, src/components/deck/default-deck.js, src/components/deck/index.js, src/components/deck/modes.js, src/components/slide/slide.js, src/hooks/use-aspect-ratio-fitting.js, src/print-mode/index.js, src/theme/index.js, src/theme/print-theme.js, src/utils/constants.js, yarn.lock
Adds export and print mode to Spectacle v7
Export Mode: A PDF-exportable version of slides in sequential order with the default theme
Print Mode: A PDF-exportable (and printable) version of slides in sequential order using the print theme
This also adds bi-directional syncing for query params for different modes and keyboard shortcuts.
Export Mode Left, Print Mode Right
The goal is to ensure each slide is best scaled per-page by default. Inside Chrome you can then choose to put multiple pages on a slide. Previously slides could get cut off so this is a fix compared to v6.
=> Export and Print Mode

package.json, src/hooks/use-presentation.js, src/hooks/use-presentation.test.js, yarn.lock
Use `react-testing-library/hooks` to test the `usePresentation` hook with the connection functions. The key is to ensure the connection object which is assigned in a Promise to a React state exists before calling a function. We do this with `await waitForValueToChange` and providing the correct selector of the connection object.
=> v7: Update usePresentation hook tests.

docs/content/api-reference.md, src/components/markdown/markdown.js
1. Fixed Notes component for Markdown slides
2. Updated documentation for the new Markdown components
3. Added migration guide for v7
=> Markdown: Fixes and Documentation

examples/js/index.js
Converts the `SlideFragments` and `Presentation` from being function declarations to arrow functions in `examples/js/index.js` file. Since they are arrow functions now I also removed the `return` statement
=> Convert functions to arrow functions for js examples

src/components/code-pane.js
Swaps out `setImmediate` with `requestAnimationFrame`. Verified the scrolling for animation highlight groups still work and it scrolls to the correct spot for long CodePanes.
Addresses #985
=> Swap setImmediate with requestAnimationFrame

src/components/__snapshots__/typography.test.js.snap, src/components/typography.js
`<Text />` has container styles as it's used typically top-level of a slide like `Heading`. `Link` however is usually inline a `Box` or `List`. This fixes the bug where there are additional margin styles attached to `Link`.
=> Fix Link styles to not use Text container styles.

docs/content/api-reference.md, src/components/deck/deck.js, src/components/deck/index.js, src/components/print-mode/index.js, src/print-mode/index.js
For `exportMode` which is designed for generating a PDF output of the deck, set the page size using CSS print media queries to the correct paper size which maps to the deck theme's slide size.
=> fix: Ensure correct page size for export mode is default

__mocks__/use-resize-observer.js, docs/content/api-reference.md, examples/js/index.js, index.d.ts, jest.config.js, src/components/markdown/markdown.js, src/components/markdown/markdown.test.js, src/test-utils/empty-module.js, src/test-utils/test-setup.js, src/utils/mdx-component-mapper.js
This PR adds a boolean prop `animateListItems` to the `Markdown` suite of components that automatically transforms MD list items into `Appear > ListItem`. This allows a user to provide MD like:
```jsx
<MarkdownSlide animateListItems>
{`
- One
- Two
- Three
`}
</MarkdownSlide>
```
and have the list items appear in one at a time.
This addresses issue #968.
I have added some Jest/Enzyme tests to test this new prop. I also added an example to the JS example deck that uses this new prop, which can be used to verify that the list items are animating in accordingly.
=> Md list appear

docs/content/api-reference.md, examples/js/index.js, examples/one-page.html, index.d.ts, src/components/markdown/markdown.js, src/components/markdown/markdown.test.js
This PR allows the user to pass a `componentProps` prop to the `Markdown` suite of components, and these props will be passed down to each individual component generated by the MD conversion process. E.g.,
```jsx
<MarkdownSlide componentProps={{ backgroundColor: 'red', color: 'blue' }}># Ugly header</MarkdownSlide>
```
will style the header with a color of blue, background of red. This gives the user some control over how their markdown components render elements.
Tests added to `markdown.test.js` to test these changes. You can also try the `componentProps` prop out within the JS example slides.
=> MD component prop pass-thru

index.d.ts, src/components/notes.js, src/index.js
Projects that consume or sit on top of Spectacle might need access to the Deck and Slide Contexts. Additionally the defaultTheme should have always been exported so users could build upon it. This also fixes a bug where Notes requires children.
Tested by linking the repo and consuming the types in a sample project.
=> Export Contexts, Theme. Update types.

src/components/markdown/markdown.js
This PR removes some default prop values to avoid over re-rendering that was causing issues with animated elements in MD components.
Linting/Jest tests passed, tested using JS example template.
=> Don't default values in MD components

index.d.ts
Uses the correct prop definitons for the `Flexbox` component. `StyledSystem.FlexProps` revers to the `flex` CSS property whereas `StyledSystem.FlexboxProps` revers to the whole collection of configurable flexbox CSS properties.
=> Use StyledSystems FlexboxProps type definition

index.d.ts
We are exporting `indentNormalizer` but do not have it as part of our typedefs. This adds it.
Tested by linking the project to another repo that uses typescript and ensuring the type is working.
=> Add missing type for indentNormalizer

docs/content/api-reference.md, index.d.ts, src/components/code-pane.js
This simplifies our theme imports to a single default dark theme and requires the user to import any custom themes in their own deck. This reduces the overall bundle size, but could potentially result in any usages of a string-based Prism theme `CodePane` to stop rendering.
To ensure the import doesn't break consumers that don't transform node modules, this was linked to a project to verify the cjs usage did not throw an `export` keyword error.
=> CodePane Syntax Theme Import Fix

package.json, src/components/deck/deck.js, src/components/deck/default-deck.js, src/components/slide/slide.js, yarn.lock
On mobile devices users can swipe left to advance slide and right to regress slide.
Fixes #984 
Feature to address [Issue#984](https://github.com/FormidableLabs/spectacle/issues/984)
=> Allow mobile device users to advance + regress slides with touch controls

docs/content/api-reference.md, src/components/appear.js, src/hooks/use-steps.js
Simplify `Appear` elements by removing useAnimatedSteps. `Appear` elements can now be nested within each other.
=> remove useAnimatedSteps from use-hooks.js

examples/js/index.js, examples/one-page.html, scripts/one-page.js
Adds a 2x2 center-content grid layout using built-in Spectacle Grid and FlexBox components to the JS example 
Adds a demonstration of how to use a 2x2 center-content grid using JSX
=> Demo Update: Add 2x2 Grid example to JS demo

src/index.js
`useMousetrap` is a default export, not named. This fixes the index file.
=> Fix export for useMousetrap

CHANGELOG.md, package.json, src/components/markdown/markdown.js, src/components/markdown/markdown.test.js, yarn.lock
This PR adds raw HTML support like normal Markdown. Our present scheme strips out all tags leaving only text.
My use case is wanting things like font-awesome icon additions which have no clear path of introduction other than HTML and other than that I'd rather be in markdown 😉 
Added a unit test and tested in the deck I'm working on that I'd want this support on.
This PR does add dangerous HTML, which is seems only risky if your deck uses outside input. I didn't see anywhere in the docs that we note previous behavior stripped HTML tags in MD, but maybe we might want to:
1. Evaluate risks of this new behavior? If risky, put behind an option instead?
2. Update the docs somewhere?
=> Feature: Add raw HTML support to markdown.

.gitignore, CHANGELOG.md, docs/content/api-reference.md, docs/content/props.md, examples/js/index.js, examples/one-page.html, index.d.ts, src/components/deck/deck.js, src/components/slide/slide.js, src/components/transitions/index.js, src/index.js
Adds support for custom transitions and two built-in transition objects: Fade and Slide. Slide is the default transitions for decks. Slides can have custom transitions that override the default Deck transition style on a per-slide basis.
- Updates one page and JS examples
- Updates documentation 
Added examples to both the OnePage and JS Decks.
=> Add support for custom transitions.

CHANGELOG.md, docs/content/api-reference.md, examples/js/index.js, index.d.ts, src/components/code-pane.js, src/components/deck/deck.js
Fixes `showLineNumbers` to be a prop and not have `true` as a hard coded value. Also ensures the theme size is correctly passed to the ThemeProvider.
Fixes #1024 
Tested via the example deck by providing a custom theme size and a new number-less code pane example.
=> Fixed showLineNumbers and theme sizing for CodePane.

src/components/code-pane.js, src/components/fullscreen.js, src/components/markdown/markdown.js, src/components/progress.js
Forwards refs to CodePane, FullScreen, Markdown and Progress components so that the internal elements can be referenced externally.
Tested by adding a ref to each of the components in question on the example/js project to confirm that they are being forwarded and set correctly:
=> Forward refs on components 

docs/src/screens/home/_content.js
Updates "Get Started" documentation link to be relative to page instead of relative to root.
Current documentation link goes to `https://formidable.com/docs/basic-concepts/` which can fail if don't visit the base page first and even then seems to intermittently fail and show a 404 page. The link as is would also break if a user were to bookmark it. This change updates it to be `https://formidable.com/open-source/spectacle/docs/basic-concepts/`
Locally confirmed link works as expected
=> Bug: Update docs link relativity

docs/content/api-reference.md, docs/content/props.md, index.d.ts, src/components/code-pane.js, src/components/fullscreen.js, src/components/markdown/markdown.js, src/components/progress.js
This PR adds styled-system functions to a few components:
**Layout**
- Markdown
- CodePane
**Position**
- Markdown
- CodePane
- FullScreen
- Progress
Tested manually by adding position/layout props to each of the components listed above.
=> Add styled-system position and layout functions to components

CHANGELOG.md, src/components/slide/slide.tsx
Ensures slides with background images do not disappear in export and overview modes. The reason it was breaking is any animated or spring styles never get activated in those modes so we need to nullify them.
Fixes #1100 
=> fix: ensure background doesn't disappear in export/overview mode with a bk image.

docs/content/api-reference.md, src/components/deck/deck.tsx, src/components/presenter-mode/index.tsx, src/components/print-mode/index.tsx, src/components/slide/slide.tsx
Adds a backgroundImage prop to Deck, DeckInternal and DeckContext. In Slide component the backgroundImage from Deck will be used if none is provided.
Fixes #1104 
Tested changes locally in the provided example.
=> Allow for same background image in all slides #1104

src/components/markdown/markdown.test.tsx, src/components/markdown/markdown.tsx
Speculate was ignoring soft line returns for inline paragraph styles in slides created via markdown. Now the markdown slides accurately reflect each line break.
**Before:**
**After:**
A unit test in `markdown.test.ts` checks that line breaks are correctly added for inline elements
=> Fix: Newlines in markdown slides correctly render line breaks

CHANGELOG.md, examples/one-page.html, src/components/deck/deck.tsx, src/components/presenter-mode/index.tsx, src/components/print-mode/index.tsx, src/components/slide/slide.tsx, src/components/template-wrapper.tsx, src/hooks/use-slides.tsx
- Moved the deck-wide template up to deck level in default mode so that it persists between slides.
- Fixed deck level templates not being displayed in presenter, print and export modes.
Completes #1106 and paves the way for #1105.
To persist deck-wide templates between slides, I needed to move the rendering of the deck template up to deck level. If the slide has a slide-specific template however, we should not render the deck template, but render the slide template instead. For this, I needed to know whether the active slide had a slide-specific template at deck level. I added a `data-slide-has-template` attribute to the slides placeholder and extended the existing `useCollectSlides` hook, which we use to to surface slide ids to the deck, to also contain information about which slides …
=> Feat: Persist deck template between slides

CHANGELOG.md, src/components/slide/slide.tsx
Before, only the first slide was displaying when performing the print / export to pdf actions in print and export modes in Firefox. After this change, all of the slides should display.
Fixes #1077 
Before:
https://user-images.githubusercontent.com/8139746/173054235-20e4f158-f674-4467-8e8a-1acbdb91006c.mov
And after:
https://user-images.githubusercontent.com/8139746/173054251-b2948960-3184-422d-a6d2-75763b78ab24.mov
Tested before and after in Firefox and across all the modes in Chrome to make sure the change is O.K.
=> fix: only the first page showing in export and print modes in Firefox

CHANGELOG.md, docs/content/api-reference.md, docs/content/props.md, examples/js/index.js, examples/md/index.js, examples/one-page.html, examples/typescript/index.tsx, src/components/animated-progress.test.tsx, src/components/animated-progress.tsx, src/components/progress.tsx, src/components/slide/slide.tsx, src/index.ts
- Added an `<AnimatedProgress />` component
https://user-images.githubusercontent.com/8139746/172902189-2c763576-7a96-4353-aa59-4ac517f2bd7a.mov
Has `color`, `size` and `pacmanColor` props. I didn't want to make assumptions so Pacman defaults to the `color` prop if not defined, but with `<Pacman pacmanColor="yellow" />` we can easily achieve:
https://user-images.githubusercontent.com/8139746/172902617-31f04464-2934-4b80-9a52-d70fc6e56b52.mov
The size of the circles is `7.5px` by default with a larger margin (to make space for the Pacman) vs `10px` for circles in the `Progress` component. This means the two can be swapped out easily at default sizing. One above the other for comparison:
Also gracefully support presentations with a lot of slides that causes the circles to wrap: …
=> Add AnimatedProgress component

examples/js/index.js, examples/one-page.html
Since upgrading to react 18, the one page example has unfortunately stopped working if re-built. The one page example has `react-dom` loaded as a global from a CDN, but the js example uses a named import for `createRoot`.
This leads to `import { createRoot } from 'react-dom/client';` being included in the output of the one page example which it's not able to resolve and `const root = createRoot(...);` where `createRoot` can't be found.
Changing the `react-dom` import to a default in the js example, results in the one page example omitting the default import from it's output and referencing `ReactDOM.createRoot(...)` where it's able to find `ReactDOM` in global scope, having been loaded from the CDN.
=> chore: change react-dom to a global import in the js example to fix one page example

docs/src/screens/home/_content.js
With pnpm restructuring, demo url broke (whoops). This PR fixes that.
=> Update demo url

packages/spectacle/src/components/code-pane.tsx
[react-syntax-highlighter](https://github.com/react-syntax-highlighter/react-syntax-highlighter) no longer supports `lineNumberProps` but it does support inline styles with `lineNumberStyle`.
Fixes #1137 
- [ x] Bug fix (non-breaking change which fixes an issue)
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.
- `example/js/index.js` to test fix
1. `pnpm run build-examples`
2. `pnpm run start:js`
- Notice the console warning `Warning: React does not recognize the 'lineNumberProps '...` is no …
=> Replaced 'lineNumberProps' with 'lineNumberStyle'

.github/workflows/release.yml, .npmrc, examples/js/package.json, examples/md/package.json, examples/typescript/package.json, package.json, packages/cli/package.json, pnpm-lock.yaml
I filed #1156 to track the issue with `pnpm install --fix-lockfile` and the short answer is: (1) it appears to be some bug, and (2) I don't know how to fix it easily.
Fortunately, `pnpm install` alone should generate `pnpm-lock.yaml` changes that we need to re-commit at the end of changeset version, so I've just switched to that.
Separately, I've removed all `workspace:` prefixes for cross-project `spectacle` dependencies because (1) they are not needed and (2) the complicate examples / other projects release-wise and confusion-wise because they are PNPM dependent artifacts.
=> Infra: bandaid version release

packages/spectacle/src/components/animated-progress.tsx
It's very minor but noticed the the sides of the Pacman didn't overlap in the earlier presentation. Thought the 0.1px box-shadow would have be enough when I first implemented but needs to be bigger.
Before:
https://user-images.githubusercontent.com/8139746/181323673-8ba18345-1ad2-4709-ba43-db0c173f3e63.mov
After:
https://user-images.githubusercontent.com/8139746/181323885-51dc587b-a0b3-4703-98b0-9ea73ed15532.mov
=> fix: space between pacman sides as they move

.changeset/tough-jokes-learn.md, packages/create-spectacle/package.json
This PR slims up the `bin` field for `create-spectacle` (since we only have one executable), and creates a changeset for a minor release. We'll see if publishing "just works" with changesets 🤔
=> `create-spectacle` first minor release

.changeset/hip-trains-flash.md, packages/create-spectacle/src/cli.ts, packages/create-spectacle/src/templates/file-writers.ts, packages/create-spectacle/src/templates/gitignore.ts, packages/create-spectacle/src/templates/readme.ts
This PR adds README/.gitignore templates for the `create-spectacle` outputs.
=> `create-spectacle`: README/gitignore templates

.changeset/tricky-drinks-listen.md, packages/create-spectacle/src/cli.ts
Address #1199 
Since `onepage` generates a single HTML file, but other deck types create a directory – we need to have a bit of a logic fork for determining whether or not we'll be overwriting (and when to prompt the user to confirm an overwrite). The approach here is to just move the `type` prompt right after `name` (but before the overwrite confirmation), so we can appropriately determine _when_ we need to overwrite (based on both `type` and `name`).
=> `create-spectacle`: Better check for overwrite

.changeset/little-peaches-jump.md, docs/api-reference.md, packages/spectacle/src/components/slide-layout.test.tsx, packages/spectacle/src/components/slide-layout.tsx
Description
The changes in the PR add four new types of Slide Layouts: Section, Statement, Big fact, and Quote. These layouts were modeled after Keynote slide templates with the goal of making slide creation quicker and easier for common use cases.
Type of Change
[ x ] New feature (non-breaking change which adds functionality)
How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.
The changes include adding new tests in packages/spectacle/src/components/slide-layout.test.tsx
While developing the feature, I manually consumed the layout components in the Presentation deck in index.tsx
Checklist: (Feel free to delete this section upon completion)
[ …
=> feat: Add new slide layouts: section, statement, big fact, quote.

docs/api-reference.md, packages/spectacle/src/components/slide-layout.test.tsx, packages/spectacle/src/components/slide-layout.tsx
This PR builds off of #1209, tweaks just a couple of very minor things:
- For `SlideLayout.BigFact`, use `children` for the fact prop (instead of a separate prop).
- For `SlideLayout.Quote`, use `children` for the quote prop (instead of a separate prop).
- Updates docs accordingly.
=> Slide layout tweaks

CONTRIBUTING.md, docs/themes.md
I used the [Grammarly extension for VS Code](https://marketplace.visualstudio.com/items?itemName=znck.grammarly&ssr=false#overview) to find issues.
Update typos in docs
N/A
=> Docs: fix typos

.changeset/tiny-buses-fold.md, packages/spectacle/src/components/markdown/markdown.tsx
Fixes a bug where a Markdown component inside a Deck template would break Spectacle. The previous implementation of Markdown always creates a Notes node tree, even with undefined children if there are no notes, which cannot exist on a template as it's not a slide. This verifies there is note content before building the Notes node tree.
Add a `<Markdown />` component with text content to a Deck template before this change and see Spectacle break and fail to render. Check it after and see it correctly render the Markdown component. 
Example below showing a Markdown component on the template and notes inside a Markdown slide verifying no regressions introduced.
=> Fix Markdown rendering inside templates.

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/question.md, .github/PULL_REQUEST_TEMPLATE.md
I converted most of the instructional text for each section into comments, because the ambiguity about whether people should delete them or not usually results in a lot of them ending up in issues that are submitted, adding to visual clutter and making the important information harder to find.
I also updated the codesandbox links that are referenced to a couple that have been updated to the latest dependencies, one for JS and one for TS. Those are currently under my personal codesandbox account, but we can fork them over to any other (company?) account if there are concerns about maintaining them. 
Github-facing only
N/A
=> Clean up issue and PR templates

.changeset/three-bikes-unite.md, packages/spectacle/src/index.ts
`useSteps`, in spite of being in [the documentation](https://formidable.com/open-source/spectacle/docs/api-reference#usesteps), is not currently exported from the library. This PR exports it.
The PR was inspired by #1019 
It has not been tested. The hook is used internally without issue, and the export didn't throw errors and shows its TypeScript type as expected.
=> Export useSteps

.github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/question.md, .github/PULL_REQUEST_TEMPLATE.md, README.md, packages/spectacle/README.md
Fixes some broken links in the READMEs and comments out one last line in the PR request template.
More direct docs link carried over from #952 
Internal/GitHub-facing-only. The docs site is not affected because only READMEs from GitHub are touched.
N/A
=> Docs and PR template tweaks

.changeset/gentle-berries-judge.md, packages/spectacle/src/components/appear.tsx, packages/spectacle/src/components/deck/deck.test.tsx, packages/spectacle/src/components/deck/deck.tsx, packages/spectacle/src/components/slide/slide.tsx, packages/spectacle/src/hooks/use-deck-state.ts, packages/spectacle/src/utils/use-auto-play.test.ts, packages/spectacle/src/utils/use-auto-play.ts
The `autoPlayLoop` prop did not actually make the slideshow loop when autoplaying.
The fix for that was fairly straightforward, but uncovered another bug - any `Appear` or `Stepper` components on the final slide would get skipped over when jumping from the final slide to the start. That required reworking the slide logic to wrap around to the start when the final step of the final slide was exceeded.
That again, was relatively straightforward, but uncovered another bug - animations occurring when wrapping from the end to the start of the slideshow were fairly rough, with slides coming and going seemingly randomly. A little work on existing internal logic fixed it for most cases, but due to the nature of the existing animation logic, I was unable to find a simple solution to the rough …
=> Fix autoPlayLoop

.changeset/serious-seals-divide.md, docs/api-reference.md, packages/spectacle/src/components/appear.tsx, packages/spectacle/src/hooks/use-steps.tsx
This change provides better error messages when useSteps or stepper components are used in the wrong context.
Fixes #1233
It hasn't been. The destructuring statements that appeared where the error throwing now occurs would throw errors anyway for the same conditions.
=> Better error messages for useSteps and stepper components

packages/spectacle/src/hooks/use-broadcast-channel.ts
This commit wraps the window for safe usage in an SSR env (like next.js)
This should be a non functional change for any users running only in browser
This has been run locally using SSR
=> add a wrapper to make window safe for SSR

.changeset/swift-bears-grow.md, docs/api-reference.md, docs/extensions.md, docs/faq.md, docs/props.md, docs/slide-layouts.md, docs/themes.md, docs/tutorial.md, packages/spectacle/src/hooks/use-broadcast-channel.ts
Updates the order of the documentation sidebar and fixes one of the labels.
Previous:
New:
=> Docs: Update sidebar order and text

docs/api-reference.md, docs/themes.md
Includes two fixes for minor docs issues I encountered:
- a syntax error when copying + pasting the template example in `docs/themes.md`
- a backwards ternary that just needed to be flipped (as I understand it)
I haven't created an issue but would be happy to. Thanks!
=> Two minor docs fixes

.changeset/tame-pugs-brake.md, docs/api-reference.md, examples/typescript/index.tsx, packages/spectacle/src/components/code-pane.tsx, packages/spectacle/src/index.ts
Currently we make folks jump through installing `react-syntax-highlighter` to use different themes. This just re-exports all the themes and merges in our current default `vsCodeDark` theme.
The size of Spectacle (esm) increases to 124.26 KB from 124.09 KB.
Added an example to the TypeScript-demo app.
=> Export code pane themes object as part of Spectacle.

.changeset/lucky-ties-rhyme.md, .changeset/tame-pugs-brake.md, docs/api-reference.md, examples/one-page/index.html, examples/typescript/index.tsx, packages/spectacle/src/components/code-pane.tsx, packages/spectacle/src/index.ts
Bumps `one-page.html` to `v10` now that it's published and verified it works from the unpkg url.
=> Set onepage to v10 release

docs/tutorial.md
Fixes the Next.js brand name, the file path and the quotes
cc @carloskelly13
=> Fix brand name, paths, quotes

.changeset/silent-drinks-chew.md, .github/workflows/release.yml
Having issues with Wireit cache not invalidating on changed files in GH Actions but locally, we want to avoid pushing releases with incomplete assets.
=> Drop wireit caching from GH Action release build

docs/advanced-concepts.md
Hi everyone, great package 🙌 
Quick PR to update the links to deployment providers (Zeit -> Vercel) and also replaced `Heroku` with `Netlify` since Heroku is not supporting free plans anymore.
=> Update deployment providers

.github/workflows/ci.yml, .npmrc, examples/md/slides.md, examples/one-page/index.html, packages/spectacle/package.json, packages/spectacle/src/components/markdown/markdown-layout-containers.tsx, packages/spectacle/src/components/markdown/markdown-slide-renderer.tsx, packages/spectacle/src/components/markdown/markdown-types.ts, packages/spectacle/src/components/markdown/markdown.test.tsx, packages/spectacle/src/components/markdown/markdown.tsx, packages/spectacle/src/index.ts, packages/spectacle/src/utils/remark-rehype-directive.test.ts, packages/spectacle/src/utils/remark-rehype-directive.ts, packages/spectacle/src/utils/separate-sections-from-json.test.ts, packages/spectacle/src/utils/separate-sections-from-json.ts, packages/spectacle/src/utils/use-timer.test.ts, pnpm-lock.yaml, website/package.json
The goal is to use directives to define section markers for custom layouts. This PR adds columns and center:
The PR updates the markdown to show the use case. No change sets as we're going to build upon this and add docs. This is the baseline to add the parsing/directive/json config object support.
=> Add base custom layout in Markdown Support

.changeset/dull-books-provide.md, packages/spectacle/src/components/appear.tsx, packages/spectacle/src/components/deck/deck.tsx, packages/spectacle/src/components/print-mode/index.tsx
Previously print mode hid content on Markdown slides and animated elements. This fix does two things:
1. Replaces the previous pixel to inch conversion with pixels to center the slide in the page
2. Ensures animated elements are always at their completion state in print mode
=> Fix print mode not showing content in Markdown slides and Animated slides

docs/extensions.md, docs/faq.md, docs/jsx-slide-layouts.md, docs/markdown-layout-containers.md, docs/md-slide-layouts.md, docs/themes.md
Adds documentation for the markdown slides layout feature we introduced in → https://github.com/FormidableLabs/spectacle/pull/1289
Addresses #1283 
Preview of docs → https://spectacle-docs-website-git-docs-md-layou-ac4133-formidable-labs.vercel.app/docs/md-slide-layouts
=> Adds documentation for Spectacle Markdown Slide Layouts

.changeset/modern-ducks-try.md, .github/workflows/create-spectacle.yml, packages/create-spectacle/.gitignore, packages/create-spectacle/package.json, packages/create-spectacle/src/generators/one-page.ts, pnpm-lock.yaml
The CLI requires the `package.json` to correctly load the right dependencies. Since it was outside of the main source package for the CLI, it was not getting included, but looked correct locally. This uses a build script to copy the package in for packaging then remove after. Below are screenshots showing a local `npm pack` with the file included and the CLI working from what `npm pack` generated.
=> Fix inclusion of spectacle package.json for CLI

.changeset/perfect-pumpkins-develop.md, packages/create-spectacle/src/cli.test.ts, packages/create-spectacle/src/cli.ts, packages/create-spectacle/src/templates/file-writers.ts, packages/create-spectacle/src/templates/index.ts, packages/create-spectacle/src/templates/markdown.ts
- Clean up the TypeScript `index.tsx` template file. This will allow us to expand the content to support new outputs down the road. Also fixes the formatting so it's nicely indented.
- Fix the `package.json` version of `spectacle` to not be a `*` which trips up pnpm and uses the version from the core library's `package.json`
- Creates a `custom.d.ts` file in the Markdown output so the import of the `.md` file does not throw an unknown type error.
Screenshot of the cleaned up, correctly indented `index.tsx`:
**How to test**
1. cd to `packages/create-spectacle`
2. run `pnpm dev`
3. Try out `md` and the two React flavors
4. `npm i && npm run start` in each output and verify they load up
=> `create-spectacle` CLI: Fix generated spectacle version, add custom types for MD build.

.changeset/cold-hairs-design.md, .changeset/funny-frogs-drop.md, examples/one-page/index.html, package.json, packages/spectacle-mdx-loader/package.json, pnpm-lock.yaml
Unfortunately, upgrading loader-utils previously didn't fully remediate all warnings. In order to get to a non-vulnerable version, we need to bump major versions.
I ran the app locally to ensure it still works, and verified there's not any breaking changes in the new major version that would affect us. 
[Link to dependabot warning for loader-utils](https://github.com/FormidableLabs/spectacle/security/dependabot/163)
Link to dependabot warning(s) for json5. [173](https://github.com/FormidableLabs/spectacle/security/dependabot/173) & [172](https://github.com/FormidableLabs/spectacle/security/dependabot/172)
loader-utils change log
https://github.com/webpack/loader-utils/blob/master/CHANGELOG.md#200-2020-03-17
Babel change log
https://github.com/babel/babel/blob/main/CHANGELOG.md#v7196-2022-1 …
=> upgrade loader-utils, ts-jest, & babel/core to fix security warnings

.github/workflows/ci.yml, .github/workflows/create-spectacle.yml, .github/workflows/release.yml
As directed by Cb, we're no longer supporting node16, and will likely not use node matrixes anymore to build / test various node versions.
This pr removes usage of node 16 and matrix, as well as works to clean up some warnings due to using older versions of Github actions such as `setup-node` and `actions/cache` etc.
Fixes #1322 & #1323
release isn't ran until a merge / push is made to master, so I cannot obtain a screenshot of the results without doing some trickery. If needed I can do so, but the changes are essentially the same as the other two files, so seems probably unnecessary.
1. I verified in the pipelines that the pnpm cache path is still retrieved and set correctly, and warnings were removed
2. I built and ran all the sample applications locally
=> stop using node 16 in pipelines / clear other pipeline warnings

.github/ISSUE_TEMPLATE/bug_report.md, CONTRIBUTING.md, README.md, docs/extensions.md, docs/index.mdx, packages/spectacle-mdx-loader/README.md, website/src/components/index/_content.ts, website/src/pages/index.tsx
As part of marking spectacle-mdx-loader repository as  read-only, I went through and audited our links within spectacle monorepo which pointed to the old repo or were out of date.
I also fixed some of the formidable.com links as well.
Once we publish this, the URL shown in npm for spectacle-mdx-loader should hopefully update to point to the monorepo instead. (it currently still points to the old repo)
verified links are good
=> chore: clean up old spectacle mdx links

examples/one-page/index.html, examples/one-page/scripts/one-page.js
Resolve issue where the one-page example does not render.
The version of react-dom was set to `>=18.0.0`, causing a conflict between the latest version `18.3.1` and react `18.2.0`. This is resolved by locking react-dom to version `18.2.0`.
=> fix: fix one-page example rendering
