- presentation/config.js
- presentation/deck.jsx
- src/deck.jsx
- src/image.jsx
- src/presenter.jsx
- src/slide.jsx
- src/transitions.jsx
- src/utils/context.jsx
- themes/default/index.js
- themes/default/print.js
- webpack.config.js
> Presenter mode

- src/deck.jsx
- src/slide.jsx
- src/utils/context.jsx
cc @ryan-roemer 
This adds custom hash values via the `id` prop on the `Slide` tag.
> Adds string hash capability

- README.markdown
- package.json
- src/base.jsx
- src/cite.jsx
- src/heading.jsx
- src/text.jsx
Please verify #106 that pacman progress remains a solid dot when you go forward or back a slide.
> fix #97, #98, #99, #100, #106

- presentation/index.js
> fix formidable url

- presentation/index.js
> add missing apostrophe

- README.markdown
- presentation/index.js
- src/components/table-header-item.js
- src/components/table-item.js
- src/components/table-row.js
- src/components/table.js
- src/index.js
- src/themes/default/print.js
- src/themes/default/screen.js
As requested in https://github.com/FormidableLabs/spectacle/issues/10#issuecomment-183889574.
> Add support for tables

- README.markdown
This supports https://github.com/FormidableLabs/spectacle-docs/pull/6
/cc @coopy
> README: Change syntax highlighting to JSX

- src/components/slide.js
This allows for style overrides at the prop level of Slide
/cc @kenwheeler
> Feature: Slide style prop

- src/components/slide.js
`this.props.className` is not required in propsTypes. It could be undefined.
> Fix undefined css class

- index.js
Reverts FormidableLabs/spectacle#210
> Revert "removing extra index file"

- src/components/s.js
Just notice this is doesn't work as expected (based on the docs) 😃
> Fix <S> component should respect base props.

- .babelrc
- package.json
* Ensure common JS modules are used for building the lib
> Use CommonJS Modules Plugin for Build Lib.

- src/actions/index.js
- src/components/block-quote.js
- src/components/cite.js
- src/components/code-pane.js
- src/components/code.js
- src/components/deck.js
- src/components/heading.js
- src/components/image.js
- src/components/link.js
- src/components/list-item.js
- src/components/list.js
- src/components/quote.js
- src/components/s.js
- src/components/table-header-item.js
- src/components/table-item.js
- src/components/table-row.js
- src/components/table.js
- src/components/text.js
- src/reducers/index.js
- src/reducers/style.js
- src/utils/base.js
Addresses https://github.com/FormidableLabs/spectacle/issues/232
> Feature add warning for minimum font size

- package.json
- src/components/__snapshots__/deck.test.js.snap
- src/components/deck.test.js
- src/components/transitionable.test.js
> Fix Deck Tests. Upgrade Jest/React.

- src/components/__snapshots__/cite.test.js.snap
- src/components/__snapshots__/presenter.test.js.snap
- src/components/__snapshots__/progress.test.js.snap
Updated some broken tests with the new snapshot content.
> Update snapshots for cite, presenter and progress.

- .travis.yml
- package.json
- webpack.config.js
- yarn.lock
Small PR to upgrade to Webpack 2.2 GM
> Upgrade to Webpack 2.2

- example/src/index.js
- src/reducers/route.js
* Fixes string-based ID to be used as a slide hash URL
* Retains bounds-checking integer based slide indexes
> Fix string-based hash url routing.

- package.json
Seeing if this has any effect on stalled CI.
> Use more conventional GitHub dependency format

- .eslintrc
- README.markdown
- src/components/__snapshots__/presenter.test.js.snap
- src/components/clock.js
- src/components/manager.js
- src/components/presenter-components.js
- src/components/presenter.js
- src/components/presenter.test.js
- src/components/time-components.js
- src/components/time.js
- src/components/timer.js
- yarn.lock
Targeting #292 issue:
- Implemented a timer mode with `Start`/`Stop`/`Reset` buttons control, counting the elapsed time through the presentation.
- Added controls (`Alt/Option + T`) to toggle between normal presentation mode (current time) and timer presentation mode.
- Re-structured the time section at the `Presenter` component:
- Created a `Time` component (`time.js`) to manage the toggle between the clock and the timer.
- Moved the clock logic from `presenter.js` to a new `Clock` component (`components/clock.js`).
- Created a `Timer` component (`timer.js) to handle the stopwatch logic and its control buttons. 
See screenshots below:
> Elapsed time stopwatch at Presenter mode

- .travis.yml
Checking if Node 7 has better luck on Travis than Node 5.
> Add Node v7 to CI config

- README.md
> Fix speling.

- README.md
https://github.com/FormidableLabs/spectacle/issues/328
> Update README to explain how to override progress bar colour

- example/src/index.js
- src/utils/base.js
Please let me know if this is what you had in mind. I took a stab at fixing #327.  First PR ever 😀.
> Enable scroll in CodePane.

- src/components/appear.js
- src/components/block-quote.js
- src/components/cite.js
- src/components/heading.js
- src/components/image.js
- src/components/link.js
- src/components/list-item.js
- src/components/quote.js
- src/components/slide.js
- src/components/table-header-item.js
- src/components/table-item.js
- src/components/text.js
Implementation for the problem raised in [#372 ](https://github.com/FormidableLabs/spectacle/issues/372).
> Style prop now has the highest precendence

- src/components/slide-components.js
Falsey values are ignored by emotion.
> Remove truthy filters on styled returns.

- src/components/component-playground.js
- src/components/component-playground.test.js
- src/components/manager.test.js
> Sync the component-playground across tabs via local storage

- .eslintrc
- src/components/__snapshots__/code-pane.test.js.snap
- src/components/__snapshots__/component-playground.test.js.snap
- src/components/code-pane.js
- src/components/component-playground.js
- Filter style props that are only used for Emotion in the Editor
components
- Edit ESLint no-unused-vars rule to ignore /^_+$/ variables
> Ignore non-DOM Editor props

- src/utils/controller.js
Found a small mistake in the controller 😬
> Pass history down correctly in src/utils/controller

- src/components/__snapshots__/heading.test.js.snap
- src/components/heading.js
> fix fit headings

- README.md
- src/components/appear.js
First, thanks so much for your hard work building Spectacle. I'm *really* enjoying it so far.
Anyhoo I'm using spectacle to build a conference talk on animation, and I needed some more robust animation options for the Appear component. They were really quick to implement and don't change the default behavior of Appears so I figured I'd PR em back in to the project. It's a tiny change but you can use it to make some really neat effects 😊
> Fancier <Appear> animations

- src/one-page.js
> Bug: Fix babel/standalone transforms

- README.md
By the way, using Emotion for this is so awesome 🕶! Great work all :)
> Fix styled import in README

- src/components/manager.js
> Reset view indexes when looping to first slide

- yarn.lock
* Fix locked URL of private npm mirror
* Removed fsevent and ran `yarn install`
> Update some dependencies (fixes #523)

- src/components/anim.js
- src/components/slide.js
> Appear fixed when slide has id

- docs/tag-api.md
> Add global style documenation

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
- .gitignore
- CONTRIBUTING.md
This PR introduces issue templates so contributors can open either a **Bug Report** or **Feature Request** issue. It also introduces a PR template with a Spectacle [CodeSandbox link](https://codesandbox.io/s/7wo8xv8nw0) so users can more easily demo their code.
> Updating contributing guidelines

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
Github introduced an extra line to our template that is upsetting prettier. This fixes that.
> Remove extra line introduced by github

- README.md
- src/components/__snapshots__/manager.test.js.snap
- src/components/deck.js
- src/components/manager.js
Hi!
This PR add the possibility to set the autoplay loop from outside (defaults to `true` cause it's the current behavior, although I'd say that `false` should make more sense eventually). 
Any suggestion/feedback/whatever will be very welcome, thanks!
_P.S. tests were already failing before this commit so I'm not sure if that's ok or not_ 💭
> Add autoplayLoop prop

- src/utils/base.js
- src/utils/base.test.js
Add `bgGraident` prop to base file 
Unit test on the `base.js` file and in presentation example I work with to debug
> add gbGradient prop to base.js file and base.test file

- README.md
> remove docs for broken feature

- src/utils/base.js
> Fixes bug where gradients weren't being applied if bgImage wasn't set

- README.md
Update the fullscreen doc to reflect the inconsistency we are running into some time using FullScreenAPI.
Fixes #654 
- This change requires a documentation update
> update fullscreen doc

- index.d.ts
- src/components/__snapshots__/text.test.js.snap
- src/components/text.js
This PR contains @JakeGinnivan's work from #518
> Fix: lineHeight not applied to UnfitText

- package.json
- src/utils/base.test.js
- yarn.lock
Very smol dependency updates, addressing a security vulnerability in an earlier version of lodash
> Minor dependency updates

- README.md
Add a link to the new Codemirror extension for Spectacle
Is a documentation change so previewed in GitHub
> Add Spectacle Codemirror extension

- src/hooks/use-presentation.js
> Add use-presentation hook file

- examples/js/test-js.js
- src/components/appear.js
- src/components/deck.js
- src/components/index.js
- src/components/layout.js
- src/components/slide.js
- src/utils/search-children-appear.js
This fixes a slide to a 16:9 ratio which fits most TVs and helps unify the presenter display view.
Template Support:
> Templates, Fix to a 16:9 aspect ratio.

- examples/js/test-js.js
- examples/mdx/test-mdx.js
- index.js
- src/components/deck/index.js
- src/components/fullscreen.js
- src/components/index.js
- src/components/layout.js
- src/components/progress.js
- src/components/slide.js
- src/hooks/use-slide.js
- src/hooks/use-url-routing.js
Add Progress and Full Screen components. Update the default template to use those.
*Windowed Mode*
*Full Screen Mode*
> Add Progress and Full Screen components.

- src/components/table.js
- src/components/typography.js
- src/index.js
Adds more styled-system options to table.
Moves tabel from `/typography.js` to `/table.js` for clarity.
> Adds more styled-system options to table and move table to table.js

- src/components/deck/index.js
Fixes the checker around how many slides there actually are.
Throws an error if there is no valid slides or no children at all. Allows for 1 slide, either `<Slide />` or something generated by Markdown Slides.
> Fix Slide Checker Logic

- src/components/image.js
- src/components/markdown.js
- src/hooks/use-transition-pipe.js
> Fix Lint Issues

- jest.config.js
- package.json
- src/components/__snapshots__/progress.test.js.snap
- src/components/__snapshots__/table.test.js.snap
- src/components/__snapshots__/typography.test.js.snap
- src/components/appear.js
- src/components/appear.test.js
- src/components/notes.test.js
- src/components/progress.js
- src/components/progress.test.js
- src/components/table.js
- src/components/table.test.js
- src/components/typography.test.js
- src/index.js
- yarn.lock
- Adds tests for all exported components
- Adds `<TableBody>` and `<TableHeader>` components as these were needed for valid DOM nesting
> [WIP] Component Tests

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
- README.md
- package.json
This PR initializes docs for our rewrite effort. There are a number of remaining to-do's to be taken care of over the course of the next week. 🙂
> Rewrite the docs

- examples/js/index.html
- examples/js/index.js
- examples/one-page.html
- src/components/__snapshots__/table.test.js.snap
- src/components/__snapshots__/typography.test.js.snap
- src/components/slide.js
- src/components/table.js
- src/components/typography.js
- src/theme/default-theme.js
- Update Demo Deck
- Fix some layout bugs in Slide and Table
> Update Demo Deck, fix some layout bugs

- package.json
- src/components/__snapshots__/component-playground.test.js.snap
- src/components/code-pane.test.js
- src/components/component-playground.js
- yarn.lock
Upgrades React Live to v2 and fixes an issue around state updating for the default content in the example. #781 
Updated tests and verified through example project.
> Upgrade React Live to v2

- .eslintrc
- src/components/image.js
- src/components/layout.js
- src/components/table.js
- src/components/typography.js
- yarn.lock
This PR opens up a discussion for new `eslint` rules. Old Spectacle applies a lot of overrides that were specific to shortcuts made in the previous code, and we can afford to lose them in favor of `prettier`'s preferences.
> Update eslint config for v6

- docs/content/api-reference.md
- docs/content/props.md
> Add anchor links + typography tag details

- .npmignore
Presently, we're publishing **all** of `docs/` which we don't want to do because it's huge. We've also got cruft like `.DS_Store` files published to npm. This PR:
- Removes `docs` from publishing (since we publish online and it's available in MD in git too)
- Removes `src` since that's not really used by our consumers.
- Hones down unused extra cruft files by limiting to `.js` files appropriately.
Here's a new sample file output:
```
$ npm pack
npm notice 
npm notice 📦  spectacle@6.0.0-alpha.3
npm notice === Tarball Contents === 
npm notice 1.2kB   LICENSE                              
npm notice 4.8kB   es/components/appear.js              
npm notice 5.2kB   lib/components/appear.js             
npm notice 1.0kB   es/components/deck/audience-deck.js  
npm notice 1.4kB …
```
> Infra: Tune npm published files.

- examples/one-page.html
Test link: https://raw.githack.com/FormidableLabs/spectacle/bug/one-page/examples/one-page.html
> Bug: one page unpkg spectacle dist link

- docs/content/api-reference.md
More docs for Appear, Markdown, FullScreen, Notes, Image, etc!
> Added more docs

- docs/content/themes.md
- examples/js/index.js
- src/components/__snapshots__/table.test.js.snap
- src/components/__snapshots__/typography.test.js.snap
- src/components/slide.js
- src/components/typography.js
- src/theme/default-theme.js
Description
- Adds documentation on the theming system
- Removes fixed values for margins for base tags. Replaces them with scale-based sizes in default theme.
> Added Theme docs, fix default margins

- docs/content/basic-concepts.md
Add documentation to get started with development
> Added Getting Started with Development

- src/components/code-pane.js
> fix codepane ignores props.theme

- src/utils/search-children-appear.js
- src/utils/search-children-appear.test.js
> Fixes Nested Appear Elements Not Being Discovered

- .travis.yml
- docs/package.json
- docs/yarn.lock
This **is** a forked PR. Let's see what happens!
> formideploy: forked PRs

- .travis.yml
> CI: conditional builds

- index.d.ts
Minor fixes to the index.d.ts file
Fixes #906
built and tested locally
VScode intellisens shows the correct types.
> fix name of prop and references to PropTypes

- package.json
- src/hooks/use-action-dispatcher.js
- src/hooks/use-aspect-ratio-fitting.js
- src/hooks/use-deck-state.js
- src/hooks/use-location-sync.js
- src/hooks/use-steps.js
- src/location-map-fns/fragment.js
- src/location-map-fns/query-string.js
- src/utils/clamp.js
- src/utils/sort-by.js
- yarn.lock
To our main-7 branch this adds a bunch of the business logic hooks and util functions from monocle. The major difference is replacing lodash functions with native ones.
> Adds business logic hooks and util functions

- src/components/deck/default-deck.js
- src/components/deck/index.js
- src/components/presenter-mode/index.js
- src/hooks/use-broadcast-channel.js
Adds the Broadcast Channel hook to function as a message bus between the Audience and Presenter View
New Feature! The URL on the audience window also updates in real time!
> Use Broadcast Channel for Dual-Browser message bus for presenting.

- src/components/slide/slide.js
Pass the current slide index and total count to the template render function.
> Pass current slide and total count to template.

- docs/content/api-reference.md
> v7: Documentation | Update props used in CodePane

- docs/content/api-reference.md
- src/components/deck/deck.js
- src/components/deck/default-deck.js
- src/print-mode/index.js
> Add customizable print props and update docs for print props

- docs/content/api-reference.md
- examples/js/index.js
- src/components/deck/deck.js
- src/utils/use-auto-play.js
- src/utils/use-auto-play.test.js
- Adds auto play support with props for looping and setting a custom a custom duration.
- Adds documentation and unit tests.
> Add Auto-Play support.

- package.json
- src/components/deck/deck.js
- src/components/presenter-mode/index.js
- yarn.lock
Currently Presenter Mode shows the last slide twice, this PR prevents the double rendering.
> Fix overflow in Presenter Mode for last slide.

- docs/content/api-reference.md
- index.d.ts
- package.json
- src/components/slide/slide.js
- yarn.lock
- Update TypeScript definitions for the v7 codebase
- Drop prop types for removed props in Slide
> Update TS defs for new v7 API.

- src/hooks/use-action-dispatcher.js
- src/hooks/use-mousetrap.js
- src/hooks/use-steps.js
add comments to better document hooks
> add comments to better document hooks

- docs/content/api-reference.md
- examples/js/index.js
- examples/one-page.html
- index.d.ts
- src/components/appear.js
- src/components/markdown/markdown.js
- src/components/markdown/markdown.test.js
- src/hooks/use-steps.js
- src/index.js
Also:
- Adds documentation for `useSteps` hook and `<Stepper>` component
- Updates documentation for `<Appear>` component
- Adds `<Stepper>` to one-page and JS examples
- Implements `<Stepper>` component
- Adds documentation for `useSteps` hook and `<Stepper>` component
- Updates documentation for `<Appear>` component
- Adds `<Stepper>` to one-page and JS examples
Fixes #1009 
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.
- [x ] I have added tests that prove my fix is effective or that my feature works
> Recreate <Stepper> component

- examples/js/index.js
- examples/one-page.html
- Re-enables "from unpkg" spectacle rather than dev only local `dist`. Fixes #1058 
- Note: the latest published spectacle on unpkg doesn't work (like if you test this PR straight up). You need to swap back into dev mode after a fresh build. Something with fragments I think.
/cc @carlos-kelly
> Bug: Fix one-page.html

- examples/one-page.html
- scripts/one-page.js
Fixed indentation in the code blocks on the one-page example.
> fix: improved indentation for code samples

- src/hooks/use-broadcast-channel.ts
This PR tweaks `use-broadcast-channel` to use refs instead of state. With React 18 strict mode, effects run twice – and our existing effects setup was not setup to handle that. This PR stabilizes things a bit, and uses refs instead of state (since we don't need these pieces of data to trigger UI rerenders).
Fixes #1130 
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.
> `use-broadcast-channel` fix

- .github/workflows/ci.yml
Reviving [this change](https://github.com/FormidableLabs/spectacle/compare/d33db77207b7e59e1af0555400a0492c4d70ea91..a8e2579bad086fb800173de2fdfd5da55d268138) that got overwritten by changesets action.
> Update `ci.yml` to use `paths-ignore`

- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
Small edits to the pull request and contributing guidelines 👍 
N/A - this does not affect any deployment workflows
> fixes to contributing and pull request guidelines

- .changeset/early-kids-happen.md
> Changeset for #1186

- packages/create-spectacle/package.json
> Remove private field from `create-spectacle` 

- .changeset/many-bobcats-brush.md
- package-scripts.js
- packages/spectacle/package.json
> Bug: Lib babel output is CommonJS

- .changeset/modern-lobsters-sing.md
- .github/workflows/release.yml
- packages/create-spectacle/package.json
- packages/spectacle/package.json
Adding [NPM package provenance](https://github.blog/2023-04-19-introducing-npm-package-provenance/) for Spectacle releases
N/A - when this is merged, we will see build summary on NPM website
> setting up NPM Provenance

- pnpm-lock.yaml
- website/docusaurus.config.js
- website/package.json
- Added the env vars to our Vercel deployment
> Add GTAG to Docs website

- .changeset/silver-swans-wash.md
- packages/create-spectacle/src/templates/readme.ts
Fixes #1334
This simply adds the missing backtick.
_I do not think that this is required for this fix._
_I do not think that this is required for this fix._
> fix(readme-template): add missing closing backtick

- packages/spectacle/src/components/slide-layout.tsx
Fixing some ts-ignores in the `slide-layout.tsx` by removing unnecessary typings.
Running the CI checks locally, not a functional change.
> fix(types): removing unnecessary types for the generic list utility
